/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sintetizatx.v:1" *)
module sintetizatx(IDLin, reset, clk_32f, clk_4f, data_serial_paraleloTX_sintetizado, active_serial_paraleloTX_sintetizado, IDLEOut_sintetizado);
  (* src = "sintetizatx.v:21" *)
  wire _0000_;
  (* src = "sintetizatx.v:21" *)
  wire _0001_;
  (* src = "sintetizatx.v:21" *)
  wire [7:0] _0002_;
  (* src = "sintetizatx.v:21" *)
  wire [7:0] _0003_;
  (* src = "sintetizatx.v:21" *)
  wire [31:0] _0004_;
  (* src = "sintetizatx.v:21" *)
  wire [31:0] _0005_;
  (* src = "sintetizatx.v:21" *)
  wire [7:0] _0006_;
  (* src = "sintetizatx.v:21" *)
  wire _0007_;
  (* src = "sintetizatx.v:21" *)
  wire _0008_;
  (* src = "sintetizatx.v:21" *)
  wire _0009_;
  (* src = "sintetizatx.v:21" *)
  wire _0010_;
  (* src = "sintetizatx.v:21" *)
  wire _0011_;
  (* src = "sintetizatx.v:21" *)
  wire _0012_;
  (* src = "sintetizatx.v:21" *)
  wire _0013_;
  (* src = "sintetizatx.v:21" *)
  wire _0014_;
  (* src = "sintetizatx.v:21" *)
  wire _0015_;
  (* src = "sintetizatx.v:21" *)
  wire _0016_;
  (* src = "sintetizatx.v:21" *)
  wire _0017_;
  (* src = "sintetizatx.v:21" *)
  wire _0018_;
  (* src = "sintetizatx.v:21" *)
  wire _0019_;
  (* src = "sintetizatx.v:21" *)
  wire _0020_;
  (* src = "sintetizatx.v:21" *)
  wire _0021_;
  (* src = "sintetizatx.v:21" *)
  wire _0022_;
  (* src = "sintetizatx.v:21" *)
  wire _0023_;
  (* src = "sintetizatx.v:21" *)
  wire _0024_;
  (* src = "sintetizatx.v:21" *)
  wire _0025_;
  (* src = "sintetizatx.v:21" *)
  wire _0026_;
  (* src = "sintetizatx.v:21" *)
  wire _0027_;
  (* src = "sintetizatx.v:21" *)
  wire _0028_;
  (* src = "sintetizatx.v:21" *)
  wire _0029_;
  (* src = "sintetizatx.v:21" *)
  wire _0030_;
  (* src = "sintetizatx.v:21" *)
  wire _0031_;
  (* src = "sintetizatx.v:21" *)
  wire _0032_;
  (* src = "sintetizatx.v:21" *)
  wire _0033_;
  (* src = "sintetizatx.v:21" *)
  wire _0034_;
  (* src = "sintetizatx.v:21" *)
  wire _0035_;
  (* src = "sintetizatx.v:21" *)
  wire _0036_;
  (* src = "sintetizatx.v:21" *)
  wire _0037_;
  (* src = "sintetizatx.v:21" *)
  wire _0038_;
  (* src = "sintetizatx.v:21" *)
  wire _0039_;
  (* src = "sintetizatx.v:21" *)
  wire _0040_;
  (* src = "sintetizatx.v:21" *)
  wire _0041_;
  (* src = "sintetizatx.v:21" *)
  wire _0042_;
  (* src = "sintetizatx.v:21" *)
  wire _0043_;
  (* src = "sintetizatx.v:21" *)
  wire _0044_;
  (* src = "sintetizatx.v:21" *)
  wire _0045_;
  (* src = "sintetizatx.v:21" *)
  wire _0046_;
  (* src = "sintetizatx.v:21" *)
  wire _0047_;
  (* src = "sintetizatx.v:21" *)
  wire _0048_;
  (* src = "sintetizatx.v:21" *)
  wire _0049_;
  (* src = "sintetizatx.v:21" *)
  wire _0050_;
  (* src = "sintetizatx.v:21" *)
  wire _0051_;
  (* src = "sintetizatx.v:21" *)
  wire _0052_;
  (* src = "sintetizatx.v:21" *)
  wire _0053_;
  (* src = "sintetizatx.v:21" *)
  wire _0054_;
  (* src = "sintetizatx.v:21" *)
  wire _0055_;
  (* src = "sintetizatx.v:21" *)
  wire _0056_;
  (* src = "sintetizatx.v:21" *)
  wire _0057_;
  (* src = "sintetizatx.v:21" *)
  wire _0058_;
  (* src = "sintetizatx.v:21" *)
  wire _0059_;
  (* src = "sintetizatx.v:21" *)
  wire _0060_;
  (* src = "sintetizatx.v:21" *)
  wire _0061_;
  (* src = "sintetizatx.v:21" *)
  wire _0062_;
  (* src = "sintetizatx.v:21" *)
  wire _0063_;
  (* src = "sintetizatx.v:21" *)
  wire _0064_;
  (* src = "sintetizatx.v:21" *)
  wire _0065_;
  (* src = "sintetizatx.v:21" *)
  wire _0066_;
  (* src = "sintetizatx.v:21" *)
  wire _0067_;
  (* src = "sintetizatx.v:21" *)
  wire _0068_;
  (* src = "sintetizatx.v:21" *)
  wire _0069_;
  (* src = "sintetizatx.v:21" *)
  wire _0070_;
  (* src = "sintetizatx.v:21" *)
  wire _0071_;
  (* src = "sintetizatx.v:21" *)
  wire _0072_;
  (* src = "sintetizatx.v:21" *)
  wire _0073_;
  (* src = "sintetizatx.v:21" *)
  wire _0074_;
  (* src = "sintetizatx.v:21" *)
  wire _0075_;
  (* src = "sintetizatx.v:21" *)
  wire _0076_;
  (* src = "sintetizatx.v:21" *)
  wire _0077_;
  (* src = "sintetizatx.v:21" *)
  wire _0078_;
  (* src = "sintetizatx.v:21" *)
  wire _0079_;
  (* src = "sintetizatx.v:21" *)
  wire _0080_;
  (* src = "sintetizatx.v:21" *)
  wire _0081_;
  (* src = "sintetizatx.v:21" *)
  wire _0082_;
  (* src = "sintetizatx.v:21" *)
  wire _0083_;
  (* src = "sintetizatx.v:21" *)
  wire _0084_;
  (* src = "sintetizatx.v:21" *)
  wire _0085_;
  (* src = "sintetizatx.v:21" *)
  wire _0086_;
  (* src = "sintetizatx.v:21" *)
  wire _0087_;
  (* src = "sintetizatx.v:21" *)
  wire _0088_;
  (* src = "sintetizatx.v:21" *)
  wire _0089_;
  (* src = "sintetizatx.v:21" *)
  wire _0090_;
  (* src = "sintetizatx.v:21" *)
  wire _0091_;
  (* src = "sintetizatx.v:21" *)
  wire _0092_;
  (* src = "sintetizatx.v:21" *)
  wire _0093_;
  (* src = "sintetizatx.v:21" *)
  wire _0094_;
  (* src = "sintetizatx.v:21" *)
  wire _0095_;
  (* src = "sintetizatx.v:21" *)
  wire _0096_;
  (* src = "sintetizatx.v:12" *)
  wire _0097_;
  (* src = "sintetizatx.v:4" *)
  wire _0098_;
  (* src = "sintetizatx.v:11" *)
  wire _0099_;
  (* src = "sintetizatx.v:15" *)
  wire _0100_;
  (* src = "sintetizatx.v:15" *)
  wire _0101_;
  (* src = "sintetizatx.v:15" *)
  wire _0102_;
  (* src = "sintetizatx.v:15" *)
  wire _0103_;
  (* src = "sintetizatx.v:15" *)
  wire _0104_;
  (* src = "sintetizatx.v:15" *)
  wire _0105_;
  (* src = "sintetizatx.v:15" *)
  wire _0106_;
  (* src = "sintetizatx.v:15" *)
  wire _0107_;
  (* src = "sintetizatx.v:16" *)
  wire _0108_;
  (* src = "sintetizatx.v:16" *)
  wire _0109_;
  (* src = "sintetizatx.v:16" *)
  wire _0110_;
  (* src = "sintetizatx.v:16" *)
  wire _0111_;
  (* src = "sintetizatx.v:16" *)
  wire _0112_;
  (* src = "sintetizatx.v:16" *)
  wire _0113_;
  (* src = "sintetizatx.v:16" *)
  wire _0114_;
  (* src = "sintetizatx.v:16" *)
  wire _0115_;
  (* src = "sintetizatx.v:18" *)
  wire _0116_;
  (* src = "sintetizatx.v:18" *)
  wire _0117_;
  (* src = "sintetizatx.v:18" *)
  wire _0118_;
  (* src = "sintetizatx.v:18" *)
  wire _0119_;
  (* src = "sintetizatx.v:18" *)
  wire _0120_;
  (* src = "sintetizatx.v:18" *)
  wire _0121_;
  (* src = "sintetizatx.v:18" *)
  wire _0122_;
  (* src = "sintetizatx.v:18" *)
  wire _0123_;
  (* src = "sintetizatx.v:18" *)
  wire _0124_;
  (* src = "sintetizatx.v:18" *)
  wire _0125_;
  (* src = "sintetizatx.v:18" *)
  wire _0126_;
  (* src = "sintetizatx.v:18" *)
  wire _0127_;
  (* src = "sintetizatx.v:18" *)
  wire _0128_;
  (* src = "sintetizatx.v:18" *)
  wire _0129_;
  (* src = "sintetizatx.v:18" *)
  wire _0130_;
  (* src = "sintetizatx.v:18" *)
  wire _0131_;
  (* src = "sintetizatx.v:18" *)
  wire _0132_;
  (* src = "sintetizatx.v:18" *)
  wire _0133_;
  (* src = "sintetizatx.v:18" *)
  wire _0134_;
  (* src = "sintetizatx.v:18" *)
  wire _0135_;
  (* src = "sintetizatx.v:18" *)
  wire _0136_;
  (* src = "sintetizatx.v:18" *)
  wire _0137_;
  (* src = "sintetizatx.v:18" *)
  wire _0138_;
  (* src = "sintetizatx.v:18" *)
  wire _0139_;
  (* src = "sintetizatx.v:18" *)
  wire _0140_;
  (* src = "sintetizatx.v:18" *)
  wire _0141_;
  (* src = "sintetizatx.v:18" *)
  wire _0142_;
  (* src = "sintetizatx.v:18" *)
  wire _0143_;
  (* src = "sintetizatx.v:18" *)
  wire _0144_;
  (* src = "sintetizatx.v:18" *)
  wire _0145_;
  (* src = "sintetizatx.v:18" *)
  wire _0146_;
  (* src = "sintetizatx.v:18" *)
  wire _0147_;
  (* src = "sintetizatx.v:19" *)
  wire _0148_;
  (* src = "sintetizatx.v:19" *)
  wire _0149_;
  (* src = "sintetizatx.v:19" *)
  wire _0150_;
  (* src = "sintetizatx.v:19" *)
  wire _0151_;
  (* src = "sintetizatx.v:19" *)
  wire _0152_;
  (* src = "sintetizatx.v:19" *)
  wire _0153_;
  (* src = "sintetizatx.v:19" *)
  wire _0154_;
  (* src = "sintetizatx.v:19" *)
  wire _0155_;
  (* src = "sintetizatx.v:19" *)
  wire _0156_;
  (* src = "sintetizatx.v:19" *)
  wire _0157_;
  (* src = "sintetizatx.v:19" *)
  wire _0158_;
  (* src = "sintetizatx.v:19" *)
  wire _0159_;
  (* src = "sintetizatx.v:19" *)
  wire _0160_;
  (* src = "sintetizatx.v:19" *)
  wire _0161_;
  (* src = "sintetizatx.v:19" *)
  wire _0162_;
  (* src = "sintetizatx.v:19" *)
  wire _0163_;
  (* src = "sintetizatx.v:19" *)
  wire _0164_;
  (* src = "sintetizatx.v:19" *)
  wire _0165_;
  (* src = "sintetizatx.v:19" *)
  wire _0166_;
  (* src = "sintetizatx.v:19" *)
  wire _0167_;
  (* src = "sintetizatx.v:19" *)
  wire _0168_;
  (* src = "sintetizatx.v:19" *)
  wire _0169_;
  (* src = "sintetizatx.v:19" *)
  wire _0170_;
  (* src = "sintetizatx.v:19" *)
  wire _0171_;
  (* src = "sintetizatx.v:19" *)
  wire _0172_;
  (* src = "sintetizatx.v:19" *)
  wire _0173_;
  (* src = "sintetizatx.v:19" *)
  wire _0174_;
  (* src = "sintetizatx.v:19" *)
  wire _0175_;
  (* src = "sintetizatx.v:19" *)
  wire _0176_;
  (* src = "sintetizatx.v:19" *)
  wire _0177_;
  (* src = "sintetizatx.v:19" *)
  wire _0178_;
  (* src = "sintetizatx.v:19" *)
  wire _0179_;
  (* src = "sintetizatx.v:10" *)
  wire _0180_;
  (* src = "sintetizatx.v:10" *)
  wire _0181_;
  (* src = "sintetizatx.v:10" *)
  wire _0182_;
  (* src = "sintetizatx.v:10" *)
  wire _0183_;
  (* src = "sintetizatx.v:10" *)
  wire _0184_;
  (* src = "sintetizatx.v:10" *)
  wire _0185_;
  (* src = "sintetizatx.v:10" *)
  wire _0186_;
  (* src = "sintetizatx.v:10" *)
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  (* src = "sintetizatx.v:5" *)
  wire _0714_;
  (* src = "sintetizatx.v:69" *)
  wire [31:0] _0715_;
  (* src = "sintetizatx.v:84" *)
  wire [31:0] _0716_;
  wire [15:0] _0717_;
  wire [7:0] _0718_;
  wire [3:0] _0719_;
  wire [1:0] _0720_;
  wire [3:0] _0721_;
  wire [1:0] _0722_;
  wire [3:0] _0723_;
  wire [1:0] _0724_;
  wire [15:0] _0725_;
  wire [7:0] _0726_;
  wire [3:0] _0727_;
  wire [1:0] _0728_;
  wire [15:0] _0729_;
  wire [7:0] _0730_;
  wire [3:0] _0731_;
  wire [1:0] _0732_;
  wire [31:0] _0733_;
  wire [7:0] _0734_;
  wire [7:0] _0735_;
  wire [31:0] _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  (* src = "sintetizatx.v:40" *)
  wire _0741_;
  (* src = "sintetizatx.v:40" *)
  wire _0742_;
  (* src = "sintetizatx.v:53" *)
  wire _0743_;
  (* src = "sintetizatx.v:40" *)
  wire _0744_;
  (* src = "sintetizatx.v:53" *)
  wire _0745_;
  (* src = "sintetizatx.v:63" *)
  wire _0746_;
  (* src = "sintetizatx.v:63" *)
  wire _0747_;
  (* src = "sintetizatx.v:53" *)
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire [6:0] _0752_;
  wire [6:0] _0753_;
  wire [6:0] _0754_;
  wire [31:0] _0755_;
  wire [31:0] _0756_;
  wire _0757_;
  wire [31:0] _0758_;
  wire [31:0] _0759_;
  wire [31:0] _0760_;
  wire [31:0] _0761_;
  wire [7:0] _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "31" *)
  wire [31:0] _0767_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "31" *)
  wire [31:0] _0768_;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30" *)
  wire [31:0] _0769_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14 16 17 18 19 20 21 22 24 25 26 28" *)
  wire [31:0] _0770_;
  wire [31:0] _0771_;
  wire _0772_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0773_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0774_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0775_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0776_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0777_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0778_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0779_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0780_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0781_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0782_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0783_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0784_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0785_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0786_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0787_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0788_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0789_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0790_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0791_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0792_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0793_;
  (* src = "sintetizatx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0794_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0795_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0796_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0797_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0798_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0799_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0800_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0801_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0802_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0803_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0804_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0805_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0806_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0807_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0808_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0809_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0810_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0811_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0812_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0813_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0814_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0815_;
  (* src = "sintetizatx.v:84|serialparalelotx.v:69|<techmap.v>:260|<techmap.v>:222" *)
  wire _0816_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0817_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0818_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0819_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0820_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0821_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0822_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0823_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0824_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0825_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0826_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0827_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0828_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0829_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0830_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0831_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0832_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0833_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0834_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0835_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0836_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0837_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0838_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0839_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0840_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0841_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0842_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0843_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0844_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0845_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0846_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0847_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0848_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0849_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0850_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0851_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0852_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0853_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0854_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0855_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0856_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0857_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0858_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0859_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0860_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0861_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0862_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0863_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0864_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0865_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0866_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0867_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0868_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0869_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0870_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0871_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:222" *)
  wire _0872_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:229" *)
  wire _0873_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:229" *)
  wire _0874_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:229" *)
  wire _0875_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:229" *)
  wire _0876_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0877_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0878_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0879_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0880_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0881_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0882_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0883_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0884_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0885_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0886_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0887_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0888_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0889_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0890_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0891_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0892_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0893_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0894_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0895_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0896_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0897_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0898_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0899_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0900_;
  (* src = "sintetizatx.v:63|<techmap.v>:260|<techmap.v>:221" *)
  wire _0901_;
  (* src = "sintetizatx.v:12" *)
  output IDLEOut_sintetizado;
  (* src = "sintetizatx.v:4" *)
  input IDLin;
  (* src = "sintetizatx.v:11" *)
  output active_serial_paraleloTX_sintetizado;
  (* src = "sintetizatx.v:15" *)
  wire [7:0] buffer;
  (* src = "sintetizatx.v:16" *)
  wire [7:0] buffer_pasado;
  (* src = "sintetizatx.v:6" *)
  input clk_32f;
  (* src = "sintetizatx.v:7" *)
  input clk_4f;
  (* src = "sintetizatx.v:18" *)
  wire [31:0] contador;
  (* src = "sintetizatx.v:19" *)
  wire [31:0] contador_BC;
  (* src = "sintetizatx.v:10" *)
  output [7:0] data_serial_paraleloTX_sintetizado;
  (* src = "sintetizatx.v:5" *)
  input reset;
  NOT _0902_ (
    .A(_0148_),
    .Y(_0188_)
  );
  NOT _0903_ (
    .A(_0159_),
    .Y(_0189_)
  );
  NOT _0904_ (
    .A(_0173_),
    .Y(_0190_)
  );
  NOT _0905_ (
    .A(_0174_),
    .Y(_0191_)
  );
  NOT _0906_ (
    .A(_0175_),
    .Y(_0192_)
  );
  NOT _0907_ (
    .A(_0176_),
    .Y(_0193_)
  );
  NOT _0908_ (
    .A(_0177_),
    .Y(_0194_)
  );
  NOT _0909_ (
    .A(_0178_),
    .Y(_0195_)
  );
  NOT _0910_ (
    .A(_0179_),
    .Y(_0196_)
  );
  NOT _0911_ (
    .A(_0150_),
    .Y(_0197_)
  );
  NOT _0912_ (
    .A(_0151_),
    .Y(_0198_)
  );
  NOT _0913_ (
    .A(_0152_),
    .Y(_0199_)
  );
  NOT _0914_ (
    .A(_0154_),
    .Y(_0200_)
  );
  NOT _0915_ (
    .A(_0156_),
    .Y(_0201_)
  );
  NOT _0916_ (
    .A(_0157_),
    .Y(_0202_)
  );
  NOT _0917_ (
    .A(_0158_),
    .Y(_0203_)
  );
  NOT _0918_ (
    .A(_0160_),
    .Y(_0204_)
  );
  NOT _0919_ (
    .A(_0161_),
    .Y(_0205_)
  );
  NOT _0920_ (
    .A(_0162_),
    .Y(_0206_)
  );
  NOT _0921_ (
    .A(_0163_),
    .Y(_0207_)
  );
  NOT _0922_ (
    .A(_0164_),
    .Y(_0208_)
  );
  NOT _0923_ (
    .A(_0166_),
    .Y(_0209_)
  );
  NOT _0924_ (
    .A(_0167_),
    .Y(_0210_)
  );
  NOT _0925_ (
    .A(_0168_),
    .Y(_0211_)
  );
  NOT _0926_ (
    .A(_0171_),
    .Y(_0212_)
  );
  NOT _0927_ (
    .A(_0172_),
    .Y(_0213_)
  );
  NOT _0928_ (
    .A(_0108_),
    .Y(_0214_)
  );
  NOT _0929_ (
    .A(_0100_),
    .Y(_0215_)
  );
  NOT _0930_ (
    .A(_0101_),
    .Y(_0216_)
  );
  NOT _0931_ (
    .A(_0106_),
    .Y(_0217_)
  );
  NOT _0932_ (
    .A(_0127_),
    .Y(_0218_)
  );
  NOT _0933_ (
    .A(_0138_),
    .Y(_0219_)
  );
  NOT _0934_ (
    .A(_0142_),
    .Y(_0220_)
  );
  NOT _0935_ (
    .A(_0143_),
    .Y(_0221_)
  );
  NOT _0936_ (
    .A(_0144_),
    .Y(_0222_)
  );
  NOT _0937_ (
    .A(_0145_),
    .Y(_0223_)
  );
  NOT _0938_ (
    .A(_0146_),
    .Y(_0224_)
  );
  NOT _0939_ (
    .A(_0147_),
    .Y(_0225_)
  );
  NOT _0940_ (
    .A(_0117_),
    .Y(_0226_)
  );
  NOT _0941_ (
    .A(_0118_),
    .Y(_0227_)
  );
  NOT _0942_ (
    .A(_0119_),
    .Y(_0228_)
  );
  NOT _0943_ (
    .A(_0120_),
    .Y(_0229_)
  );
  NOT _0944_ (
    .A(_0121_),
    .Y(_0230_)
  );
  NOT _0945_ (
    .A(_0122_),
    .Y(_0231_)
  );
  NOT _0946_ (
    .A(_0123_),
    .Y(_0232_)
  );
  NOT _0947_ (
    .A(_0124_),
    .Y(_0233_)
  );
  NOT _0948_ (
    .A(_0125_),
    .Y(_0234_)
  );
  NOT _0949_ (
    .A(_0126_),
    .Y(_0235_)
  );
  NOT _0950_ (
    .A(_0128_),
    .Y(_0236_)
  );
  NOT _0951_ (
    .A(_0129_),
    .Y(_0237_)
  );
  NOT _0952_ (
    .A(_0130_),
    .Y(_0238_)
  );
  NOT _0953_ (
    .A(_0131_),
    .Y(_0239_)
  );
  NOT _0954_ (
    .A(_0132_),
    .Y(_0240_)
  );
  NOT _0955_ (
    .A(_0133_),
    .Y(_0241_)
  );
  NOT _0956_ (
    .A(_0134_),
    .Y(_0242_)
  );
  NOT _0957_ (
    .A(_0135_),
    .Y(_0243_)
  );
  NOT _0958_ (
    .A(_0136_),
    .Y(_0244_)
  );
  NOT _0959_ (
    .A(_0137_),
    .Y(_0245_)
  );
  NOT _0960_ (
    .A(_0140_),
    .Y(_0246_)
  );
  NOT _0961_ (
    .A(_0187_),
    .Y(_0247_)
  );
  NOT _0962_ (
    .A(_0714_),
    .Y(_0248_)
  );
  NOT _0963_ (
    .A(_0182_),
    .Y(_0249_)
  );
  NOT _0964_ (
    .A(_0183_),
    .Y(_0250_)
  );
  NOT _0965_ (
    .A(_0184_),
    .Y(_0251_)
  );
  NOT _0966_ (
    .A(_0185_),
    .Y(_0252_)
  );
  NOT _0967_ (
    .A(_0116_),
    .Y(_0253_)
  );
  NOT _0968_ (
    .A(_0170_),
    .Y(_0254_)
  );
  NAND _0969_ (
    .A(_0102_),
    .B(_0103_),
    .Y(_0255_)
  );
  NOR _0970_ (
    .A(_0101_),
    .B(_0106_),
    .Y(_0256_)
  );
  NAND _0971_ (
    .A(_0107_),
    .B(_0105_),
    .Y(_0257_)
  );
  NAND _0972_ (
    .A(_0215_),
    .B(_0104_),
    .Y(_0258_)
  );
  NOR _0973_ (
    .A(_0255_),
    .B(_0258_),
    .Y(_0259_)
  );
  NAND _0974_ (
    .A(_0256_),
    .B(_0259_),
    .Y(_0260_)
  );
  NOR _0975_ (
    .A(_0257_),
    .B(_0260_),
    .Y(_0261_)
  );
  NOT _0976_ (
    .A(_0261_),
    .Y(_0262_)
  );
  NOR _0977_ (
    .A(_0136_),
    .B(_0137_),
    .Y(_0263_)
  );
  NOR _0978_ (
    .A(_0139_),
    .B(_0140_),
    .Y(_0264_)
  );
  NAND _0979_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0265_)
  );
  NAND _0980_ (
    .A(_0240_),
    .B(_0241_),
    .Y(_0266_)
  );
  NAND _0981_ (
    .A(_0242_),
    .B(_0243_),
    .Y(_0267_)
  );
  NOR _0982_ (
    .A(_0266_),
    .B(_0267_),
    .Y(_0268_)
  );
  NAND _0983_ (
    .A(_0236_),
    .B(_0237_),
    .Y(_0269_)
  );
  NAND _0984_ (
    .A(_0238_),
    .B(_0239_),
    .Y(_0270_)
  );
  NOR _0985_ (
    .A(_0269_),
    .B(_0270_),
    .Y(_0271_)
  );
  NAND _0986_ (
    .A(_0268_),
    .B(_0271_),
    .Y(_0272_)
  );
  NOR _0987_ (
    .A(_0265_),
    .B(_0272_),
    .Y(_0273_)
  );
  NAND _0988_ (
    .A(_0232_),
    .B(_0233_),
    .Y(_0274_)
  );
  NAND _0989_ (
    .A(_0234_),
    .B(_0235_),
    .Y(_0275_)
  );
  NOR _0990_ (
    .A(_0274_),
    .B(_0275_),
    .Y(_0276_)
  );
  NOR _0991_ (
    .A(_0120_),
    .B(_0121_),
    .Y(_0277_)
  );
  NAND _0992_ (
    .A(_0228_),
    .B(_0277_),
    .Y(_0278_)
  );
  NOR _0993_ (
    .A(_0122_),
    .B(_0278_),
    .Y(_0279_)
  );
  NAND _0994_ (
    .A(_0276_),
    .B(_0279_),
    .Y(_0280_)
  );
  NOR _0995_ (
    .A(_0146_),
    .B(_0147_),
    .Y(_0281_)
  );
  NOR _0996_ (
    .A(_0117_),
    .B(_0118_),
    .Y(_0282_)
  );
  NAND _0997_ (
    .A(_0281_),
    .B(_0282_),
    .Y(_0283_)
  );
  NOR _0998_ (
    .A(_0142_),
    .B(_0143_),
    .Y(_0284_)
  );
  NOR _0999_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0285_)
  );
  NAND _1000_ (
    .A(_0284_),
    .B(_0285_),
    .Y(_0286_)
  );
  NOR _1001_ (
    .A(_0283_),
    .B(_0286_),
    .Y(_0287_)
  );
  NAND _1002_ (
    .A(_0273_),
    .B(_0287_),
    .Y(_0288_)
  );
  NOR _1003_ (
    .A(_0280_),
    .B(_0288_),
    .Y(_0289_)
  );
  NOR _1004_ (
    .A(_0138_),
    .B(_0141_),
    .Y(_0290_)
  );
  NAND _1005_ (
    .A(_0116_),
    .B(_0290_),
    .Y(_0291_)
  );
  NOR _1006_ (
    .A(_0127_),
    .B(_0291_),
    .Y(_0292_)
  );
  NAND _1007_ (
    .A(_0289_),
    .B(_0292_),
    .Y(_0293_)
  );
  NOT _1008_ (
    .A(_0293_),
    .Y(_0294_)
  );
  NOR _1009_ (
    .A(_0151_),
    .B(_0152_),
    .Y(_0295_)
  );
  NOR _1010_ (
    .A(_0153_),
    .B(_0154_),
    .Y(_0296_)
  );
  NAND _1011_ (
    .A(_0295_),
    .B(_0296_),
    .Y(_0297_)
  );
  NOR _1012_ (
    .A(_0179_),
    .B(_0149_),
    .Y(_0298_)
  );
  NAND _1013_ (
    .A(_0195_),
    .B(_0197_),
    .Y(_0299_)
  );
  NOR _1014_ (
    .A(_0297_),
    .B(_0299_),
    .Y(_0300_)
  );
  NAND _1015_ (
    .A(_0298_),
    .B(_0300_),
    .Y(_0301_)
  );
  NOR _1016_ (
    .A(_0160_),
    .B(_0163_),
    .Y(_0302_)
  );
  NOR _1017_ (
    .A(_0161_),
    .B(_0162_),
    .Y(_0303_)
  );
  NAND _1018_ (
    .A(_0302_),
    .B(_0303_),
    .Y(_0304_)
  );
  NOR _1019_ (
    .A(_0155_),
    .B(_0156_),
    .Y(_0305_)
  );
  NOR _1020_ (
    .A(_0157_),
    .B(_0158_),
    .Y(_0306_)
  );
  NAND _1021_ (
    .A(_0305_),
    .B(_0306_),
    .Y(_0307_)
  );
  NOR _1022_ (
    .A(_0304_),
    .B(_0307_),
    .Y(_0308_)
  );
  NOR _1023_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0309_)
  );
  NAND _1024_ (
    .A(_0212_),
    .B(_0309_),
    .Y(_0310_)
  );
  NOR _1025_ (
    .A(_0164_),
    .B(_0165_),
    .Y(_0311_)
  );
  NOR _1026_ (
    .A(_0166_),
    .B(_0167_),
    .Y(_0312_)
  );
  NAND _1027_ (
    .A(_0311_),
    .B(_0312_),
    .Y(_0313_)
  );
  NOR _1028_ (
    .A(_0310_),
    .B(_0313_),
    .Y(_0314_)
  );
  NAND _1029_ (
    .A(_0308_),
    .B(_0314_),
    .Y(_0315_)
  );
  NOR _1030_ (
    .A(_0301_),
    .B(_0315_),
    .Y(_0316_)
  );
  NOR _1031_ (
    .A(_0174_),
    .B(_0175_),
    .Y(_0317_)
  );
  NOR _1032_ (
    .A(_0176_),
    .B(_0177_),
    .Y(_0318_)
  );
  NAND _1033_ (
    .A(_0317_),
    .B(_0318_),
    .Y(_0319_)
  );
  NOR _1034_ (
    .A(_0148_),
    .B(_0159_),
    .Y(_0320_)
  );
  NAND _1035_ (
    .A(_0190_),
    .B(_0213_),
    .Y(_0321_)
  );
  NOR _1036_ (
    .A(_0254_),
    .B(_0321_),
    .Y(_0322_)
  );
  NAND _1037_ (
    .A(_0320_),
    .B(_0322_),
    .Y(_0323_)
  );
  NOR _1038_ (
    .A(_0319_),
    .B(_0323_),
    .Y(_0324_)
  );
  NOT _1039_ (
    .A(_0324_),
    .Y(_0325_)
  );
  NAND _1040_ (
    .A(_0316_),
    .B(_0324_),
    .Y(_0326_)
  );
  NOR _1041_ (
    .A(_0293_),
    .B(_0326_),
    .Y(_0327_)
  );
  NOR _1042_ (
    .A(_0293_),
    .B(_0325_),
    .Y(_0328_)
  );
  NAND _1043_ (
    .A(_0316_),
    .B(_0328_),
    .Y(_0329_)
  );
  NOT _1044_ (
    .A(_0329_),
    .Y(_0330_)
  );
  NAND _1045_ (
    .A(_0262_),
    .B(_0330_),
    .Y(_0331_)
  );
  NOT _1046_ (
    .A(_0331_),
    .Y(_0332_)
  );
  NAND _1047_ (
    .A(_0247_),
    .B(_0331_),
    .Y(_0333_)
  );
  NAND _1048_ (
    .A(_0187_),
    .B(_0248_),
    .Y(_0334_)
  );
  NAND _1049_ (
    .A(_0190_),
    .B(_0254_),
    .Y(_0335_)
  );
  NOR _1050_ (
    .A(_0319_),
    .B(_0335_),
    .Y(_0336_)
  );
  NAND _1051_ (
    .A(_0316_),
    .B(_0336_),
    .Y(_0337_)
  );
  NAND _1052_ (
    .A(_0213_),
    .B(_0337_),
    .Y(_0338_)
  );
  NAND _1053_ (
    .A(_0261_),
    .B(_0338_),
    .Y(_0339_)
  );
  NOT _1054_ (
    .A(_0339_),
    .Y(_0340_)
  );
  NOR _1055_ (
    .A(_0248_),
    .B(_0340_),
    .Y(_0341_)
  );
  NAND _1056_ (
    .A(_0714_),
    .B(_0339_),
    .Y(_0342_)
  );
  NOR _1057_ (
    .A(_0107_),
    .B(_0329_),
    .Y(_0343_)
  );
  NOR _1058_ (
    .A(_0342_),
    .B(_0343_),
    .Y(_0344_)
  );
  NAND _1059_ (
    .A(_0333_),
    .B(_0344_),
    .Y(_0345_)
  );
  NAND _1060_ (
    .A(_0334_),
    .B(_0345_),
    .Y(_0096_)
  );
  NAND _1061_ (
    .A(_0180_),
    .B(_0331_),
    .Y(_0346_)
  );
  NOT _1062_ (
    .A(_0346_),
    .Y(_0347_)
  );
  NOR _1063_ (
    .A(_0215_),
    .B(_0329_),
    .Y(_0348_)
  );
  NOR _1064_ (
    .A(_0347_),
    .B(_0348_),
    .Y(_0349_)
  );
  NOR _1065_ (
    .A(_0342_),
    .B(_0349_),
    .Y(_0089_)
  );
  NAND _1066_ (
    .A(_0181_),
    .B(_0331_),
    .Y(_0350_)
  );
  NOT _1067_ (
    .A(_0350_),
    .Y(_0351_)
  );
  NOR _1068_ (
    .A(_0216_),
    .B(_0329_),
    .Y(_0352_)
  );
  NOR _1069_ (
    .A(_0351_),
    .B(_0352_),
    .Y(_0353_)
  );
  NOR _1070_ (
    .A(_0342_),
    .B(_0353_),
    .Y(_0090_)
  );
  NAND _1071_ (
    .A(_0249_),
    .B(_0331_),
    .Y(_0354_)
  );
  NAND _1072_ (
    .A(_0341_),
    .B(_0354_),
    .Y(_0355_)
  );
  NOR _1073_ (
    .A(_0102_),
    .B(_0331_),
    .Y(_0356_)
  );
  NOR _1074_ (
    .A(_0355_),
    .B(_0356_),
    .Y(_0091_)
  );
  NAND _1075_ (
    .A(_0250_),
    .B(_0331_),
    .Y(_0357_)
  );
  NAND _1076_ (
    .A(_0341_),
    .B(_0357_),
    .Y(_0358_)
  );
  NOR _1077_ (
    .A(_0103_),
    .B(_0331_),
    .Y(_0359_)
  );
  NOR _1078_ (
    .A(_0358_),
    .B(_0359_),
    .Y(_0092_)
  );
  NAND _1079_ (
    .A(_0251_),
    .B(_0331_),
    .Y(_0360_)
  );
  NAND _1080_ (
    .A(_0341_),
    .B(_0360_),
    .Y(_0361_)
  );
  NOR _1081_ (
    .A(_0104_),
    .B(_0331_),
    .Y(_0362_)
  );
  NOR _1082_ (
    .A(_0361_),
    .B(_0362_),
    .Y(_0093_)
  );
  NAND _1083_ (
    .A(_0252_),
    .B(_0331_),
    .Y(_0363_)
  );
  NAND _1084_ (
    .A(_0341_),
    .B(_0363_),
    .Y(_0364_)
  );
  NOR _1085_ (
    .A(_0105_),
    .B(_0329_),
    .Y(_0365_)
  );
  NOR _1086_ (
    .A(_0364_),
    .B(_0365_),
    .Y(_0094_)
  );
  NAND _1087_ (
    .A(_0186_),
    .B(_0331_),
    .Y(_0366_)
  );
  NOT _1088_ (
    .A(_0366_),
    .Y(_0367_)
  );
  NOR _1089_ (
    .A(_0217_),
    .B(_0329_),
    .Y(_0368_)
  );
  NOR _1090_ (
    .A(_0367_),
    .B(_0368_),
    .Y(_0369_)
  );
  NOR _1091_ (
    .A(_0342_),
    .B(_0369_),
    .Y(_0095_)
  );
  NOR _1092_ (
    .A(_0248_),
    .B(_0116_),
    .Y(_0025_)
  );
  NOR _1093_ (
    .A(_0218_),
    .B(_0253_),
    .Y(_0370_)
  );
  NAND _1094_ (
    .A(_0127_),
    .B(_0116_),
    .Y(_0371_)
  );
  NOR _1095_ (
    .A(_0127_),
    .B(_0116_),
    .Y(_0372_)
  );
  NOT _1096_ (
    .A(_0372_),
    .Y(_0373_)
  );
  NAND _1097_ (
    .A(_0714_),
    .B(_0373_),
    .Y(_0374_)
  );
  NOR _1098_ (
    .A(_0370_),
    .B(_0374_),
    .Y(_0036_)
  );
  NOR _1099_ (
    .A(_0219_),
    .B(_0371_),
    .Y(_0375_)
  );
  NOT _1100_ (
    .A(_0375_),
    .Y(_0376_)
  );
  NAND _1101_ (
    .A(_0219_),
    .B(_0371_),
    .Y(_0377_)
  );
  NAND _1102_ (
    .A(_0714_),
    .B(_0377_),
    .Y(_0378_)
  );
  NOR _1103_ (
    .A(_0375_),
    .B(_0378_),
    .Y(_0047_)
  );
  NOR _1104_ (
    .A(_0289_),
    .B(_0376_),
    .Y(_0379_)
  );
  NOR _1105_ (
    .A(_0141_),
    .B(_0379_),
    .Y(_0380_)
  );
  NAND _1106_ (
    .A(_0141_),
    .B(_0375_),
    .Y(_0381_)
  );
  NOT _1107_ (
    .A(_0381_),
    .Y(_0382_)
  );
  NAND _1108_ (
    .A(_0714_),
    .B(_0381_),
    .Y(_0383_)
  );
  NOR _1109_ (
    .A(_0380_),
    .B(_0383_),
    .Y(_0050_)
  );
  NOR _1110_ (
    .A(_0220_),
    .B(_0381_),
    .Y(_0384_)
  );
  NAND _1111_ (
    .A(_0142_),
    .B(_0382_),
    .Y(_0385_)
  );
  NAND _1112_ (
    .A(_0220_),
    .B(_0381_),
    .Y(_0386_)
  );
  NAND _1113_ (
    .A(_0714_),
    .B(_0386_),
    .Y(_0387_)
  );
  NOR _1114_ (
    .A(_0384_),
    .B(_0387_),
    .Y(_0051_)
  );
  NOR _1115_ (
    .A(_0221_),
    .B(_0385_),
    .Y(_0388_)
  );
  NAND _1116_ (
    .A(_0143_),
    .B(_0384_),
    .Y(_0389_)
  );
  NAND _1117_ (
    .A(_0221_),
    .B(_0385_),
    .Y(_0390_)
  );
  NAND _1118_ (
    .A(_0714_),
    .B(_0390_),
    .Y(_0391_)
  );
  NOR _1119_ (
    .A(_0388_),
    .B(_0391_),
    .Y(_0052_)
  );
  NOR _1120_ (
    .A(_0222_),
    .B(_0389_),
    .Y(_0392_)
  );
  NAND _1121_ (
    .A(_0144_),
    .B(_0388_),
    .Y(_0393_)
  );
  NAND _1122_ (
    .A(_0222_),
    .B(_0389_),
    .Y(_0394_)
  );
  NAND _1123_ (
    .A(_0714_),
    .B(_0394_),
    .Y(_0395_)
  );
  NOR _1124_ (
    .A(_0392_),
    .B(_0395_),
    .Y(_0053_)
  );
  NOR _1125_ (
    .A(_0223_),
    .B(_0393_),
    .Y(_0396_)
  );
  NAND _1126_ (
    .A(_0145_),
    .B(_0392_),
    .Y(_0397_)
  );
  NAND _1127_ (
    .A(_0223_),
    .B(_0393_),
    .Y(_0398_)
  );
  NAND _1128_ (
    .A(_0714_),
    .B(_0398_),
    .Y(_0399_)
  );
  NOR _1129_ (
    .A(_0396_),
    .B(_0399_),
    .Y(_0054_)
  );
  NOR _1130_ (
    .A(_0224_),
    .B(_0397_),
    .Y(_0400_)
  );
  NAND _1131_ (
    .A(_0146_),
    .B(_0396_),
    .Y(_0401_)
  );
  NAND _1132_ (
    .A(_0224_),
    .B(_0397_),
    .Y(_0402_)
  );
  NAND _1133_ (
    .A(_0714_),
    .B(_0402_),
    .Y(_0403_)
  );
  NOR _1134_ (
    .A(_0400_),
    .B(_0403_),
    .Y(_0055_)
  );
  NOR _1135_ (
    .A(_0225_),
    .B(_0401_),
    .Y(_0404_)
  );
  NAND _1136_ (
    .A(_0147_),
    .B(_0400_),
    .Y(_0405_)
  );
  NAND _1137_ (
    .A(_0225_),
    .B(_0401_),
    .Y(_0406_)
  );
  NAND _1138_ (
    .A(_0714_),
    .B(_0406_),
    .Y(_0407_)
  );
  NOR _1139_ (
    .A(_0404_),
    .B(_0407_),
    .Y(_0056_)
  );
  NOR _1140_ (
    .A(_0226_),
    .B(_0405_),
    .Y(_0408_)
  );
  NAND _1141_ (
    .A(_0117_),
    .B(_0404_),
    .Y(_0409_)
  );
  NAND _1142_ (
    .A(_0226_),
    .B(_0405_),
    .Y(_0410_)
  );
  NAND _1143_ (
    .A(_0714_),
    .B(_0410_),
    .Y(_0411_)
  );
  NOR _1144_ (
    .A(_0408_),
    .B(_0411_),
    .Y(_0026_)
  );
  NOR _1145_ (
    .A(_0227_),
    .B(_0409_),
    .Y(_0412_)
  );
  NAND _1146_ (
    .A(_0118_),
    .B(_0408_),
    .Y(_0413_)
  );
  NAND _1147_ (
    .A(_0227_),
    .B(_0409_),
    .Y(_0414_)
  );
  NAND _1148_ (
    .A(_0714_),
    .B(_0414_),
    .Y(_0415_)
  );
  NOR _1149_ (
    .A(_0412_),
    .B(_0415_),
    .Y(_0027_)
  );
  NOR _1150_ (
    .A(_0228_),
    .B(_0413_),
    .Y(_0416_)
  );
  NAND _1151_ (
    .A(_0119_),
    .B(_0412_),
    .Y(_0417_)
  );
  NAND _1152_ (
    .A(_0228_),
    .B(_0413_),
    .Y(_0418_)
  );
  NAND _1153_ (
    .A(_0714_),
    .B(_0418_),
    .Y(_0419_)
  );
  NOR _1154_ (
    .A(_0416_),
    .B(_0419_),
    .Y(_0028_)
  );
  NOR _1155_ (
    .A(_0229_),
    .B(_0417_),
    .Y(_0420_)
  );
  NAND _1156_ (
    .A(_0120_),
    .B(_0416_),
    .Y(_0421_)
  );
  NAND _1157_ (
    .A(_0229_),
    .B(_0417_),
    .Y(_0422_)
  );
  NAND _1158_ (
    .A(_0714_),
    .B(_0422_),
    .Y(_0423_)
  );
  NOR _1159_ (
    .A(_0420_),
    .B(_0423_),
    .Y(_0029_)
  );
  NOR _1160_ (
    .A(_0230_),
    .B(_0421_),
    .Y(_0424_)
  );
  NAND _1161_ (
    .A(_0121_),
    .B(_0420_),
    .Y(_0425_)
  );
  NAND _1162_ (
    .A(_0230_),
    .B(_0421_),
    .Y(_0426_)
  );
  NAND _1163_ (
    .A(_0714_),
    .B(_0426_),
    .Y(_0427_)
  );
  NOR _1164_ (
    .A(_0424_),
    .B(_0427_),
    .Y(_0030_)
  );
  NOR _1165_ (
    .A(_0231_),
    .B(_0425_),
    .Y(_0428_)
  );
  NAND _1166_ (
    .A(_0122_),
    .B(_0424_),
    .Y(_0429_)
  );
  NAND _1167_ (
    .A(_0231_),
    .B(_0425_),
    .Y(_0430_)
  );
  NAND _1168_ (
    .A(_0714_),
    .B(_0430_),
    .Y(_0431_)
  );
  NOR _1169_ (
    .A(_0428_),
    .B(_0431_),
    .Y(_0031_)
  );
  NOR _1170_ (
    .A(_0232_),
    .B(_0429_),
    .Y(_0432_)
  );
  NAND _1171_ (
    .A(_0123_),
    .B(_0428_),
    .Y(_0433_)
  );
  NAND _1172_ (
    .A(_0232_),
    .B(_0429_),
    .Y(_0434_)
  );
  NAND _1173_ (
    .A(_0714_),
    .B(_0434_),
    .Y(_0435_)
  );
  NOR _1174_ (
    .A(_0432_),
    .B(_0435_),
    .Y(_0032_)
  );
  NOR _1175_ (
    .A(_0233_),
    .B(_0433_),
    .Y(_0436_)
  );
  NAND _1176_ (
    .A(_0124_),
    .B(_0432_),
    .Y(_0437_)
  );
  NAND _1177_ (
    .A(_0233_),
    .B(_0433_),
    .Y(_0438_)
  );
  NAND _1178_ (
    .A(_0714_),
    .B(_0438_),
    .Y(_0439_)
  );
  NOR _1179_ (
    .A(_0436_),
    .B(_0439_),
    .Y(_0033_)
  );
  NOR _1180_ (
    .A(_0234_),
    .B(_0437_),
    .Y(_0440_)
  );
  NAND _1181_ (
    .A(_0125_),
    .B(_0436_),
    .Y(_0441_)
  );
  NAND _1182_ (
    .A(_0234_),
    .B(_0437_),
    .Y(_0442_)
  );
  NAND _1183_ (
    .A(_0714_),
    .B(_0442_),
    .Y(_0443_)
  );
  NOR _1184_ (
    .A(_0440_),
    .B(_0443_),
    .Y(_0034_)
  );
  NOR _1185_ (
    .A(_0235_),
    .B(_0441_),
    .Y(_0444_)
  );
  NAND _1186_ (
    .A(_0126_),
    .B(_0440_),
    .Y(_0445_)
  );
  NAND _1187_ (
    .A(_0235_),
    .B(_0441_),
    .Y(_0446_)
  );
  NAND _1188_ (
    .A(_0714_),
    .B(_0446_),
    .Y(_0447_)
  );
  NOR _1189_ (
    .A(_0444_),
    .B(_0447_),
    .Y(_0035_)
  );
  NOR _1190_ (
    .A(_0236_),
    .B(_0445_),
    .Y(_0448_)
  );
  NAND _1191_ (
    .A(_0128_),
    .B(_0444_),
    .Y(_0449_)
  );
  NAND _1192_ (
    .A(_0236_),
    .B(_0445_),
    .Y(_0450_)
  );
  NAND _1193_ (
    .A(_0714_),
    .B(_0450_),
    .Y(_0451_)
  );
  NOR _1194_ (
    .A(_0448_),
    .B(_0451_),
    .Y(_0037_)
  );
  NOR _1195_ (
    .A(_0237_),
    .B(_0449_),
    .Y(_0452_)
  );
  NAND _1196_ (
    .A(_0129_),
    .B(_0448_),
    .Y(_0453_)
  );
  NAND _1197_ (
    .A(_0237_),
    .B(_0449_),
    .Y(_0454_)
  );
  NAND _1198_ (
    .A(_0714_),
    .B(_0454_),
    .Y(_0455_)
  );
  NOR _1199_ (
    .A(_0452_),
    .B(_0455_),
    .Y(_0038_)
  );
  NOR _1200_ (
    .A(_0238_),
    .B(_0453_),
    .Y(_0456_)
  );
  NAND _1201_ (
    .A(_0130_),
    .B(_0452_),
    .Y(_0457_)
  );
  NAND _1202_ (
    .A(_0238_),
    .B(_0453_),
    .Y(_0458_)
  );
  NAND _1203_ (
    .A(_0714_),
    .B(_0458_),
    .Y(_0459_)
  );
  NOR _1204_ (
    .A(_0456_),
    .B(_0459_),
    .Y(_0039_)
  );
  NOR _1205_ (
    .A(_0239_),
    .B(_0457_),
    .Y(_0460_)
  );
  NAND _1206_ (
    .A(_0131_),
    .B(_0456_),
    .Y(_0461_)
  );
  NAND _1207_ (
    .A(_0239_),
    .B(_0457_),
    .Y(_0462_)
  );
  NAND _1208_ (
    .A(_0714_),
    .B(_0462_),
    .Y(_0463_)
  );
  NOR _1209_ (
    .A(_0460_),
    .B(_0463_),
    .Y(_0040_)
  );
  NOR _1210_ (
    .A(_0240_),
    .B(_0461_),
    .Y(_0464_)
  );
  NAND _1211_ (
    .A(_0132_),
    .B(_0460_),
    .Y(_0465_)
  );
  NAND _1212_ (
    .A(_0240_),
    .B(_0461_),
    .Y(_0466_)
  );
  NAND _1213_ (
    .A(_0714_),
    .B(_0466_),
    .Y(_0467_)
  );
  NOR _1214_ (
    .A(_0464_),
    .B(_0467_),
    .Y(_0041_)
  );
  NOR _1215_ (
    .A(_0241_),
    .B(_0465_),
    .Y(_0468_)
  );
  NAND _1216_ (
    .A(_0133_),
    .B(_0464_),
    .Y(_0469_)
  );
  NAND _1217_ (
    .A(_0241_),
    .B(_0465_),
    .Y(_0470_)
  );
  NAND _1218_ (
    .A(_0714_),
    .B(_0470_),
    .Y(_0471_)
  );
  NOR _1219_ (
    .A(_0468_),
    .B(_0471_),
    .Y(_0042_)
  );
  NOR _1220_ (
    .A(_0242_),
    .B(_0469_),
    .Y(_0472_)
  );
  NAND _1221_ (
    .A(_0134_),
    .B(_0468_),
    .Y(_0473_)
  );
  NAND _1222_ (
    .A(_0242_),
    .B(_0469_),
    .Y(_0474_)
  );
  NAND _1223_ (
    .A(_0714_),
    .B(_0474_),
    .Y(_0475_)
  );
  NOR _1224_ (
    .A(_0472_),
    .B(_0475_),
    .Y(_0043_)
  );
  NOR _1225_ (
    .A(_0243_),
    .B(_0473_),
    .Y(_0476_)
  );
  NAND _1226_ (
    .A(_0135_),
    .B(_0472_),
    .Y(_0477_)
  );
  NAND _1227_ (
    .A(_0243_),
    .B(_0473_),
    .Y(_0478_)
  );
  NAND _1228_ (
    .A(_0714_),
    .B(_0478_),
    .Y(_0479_)
  );
  NOR _1229_ (
    .A(_0476_),
    .B(_0479_),
    .Y(_0044_)
  );
  NOR _1230_ (
    .A(_0244_),
    .B(_0477_),
    .Y(_0480_)
  );
  NAND _1231_ (
    .A(_0136_),
    .B(_0476_),
    .Y(_0481_)
  );
  NAND _1232_ (
    .A(_0244_),
    .B(_0477_),
    .Y(_0482_)
  );
  NAND _1233_ (
    .A(_0714_),
    .B(_0482_),
    .Y(_0483_)
  );
  NOR _1234_ (
    .A(_0480_),
    .B(_0483_),
    .Y(_0045_)
  );
  NOR _1235_ (
    .A(_0245_),
    .B(_0481_),
    .Y(_0484_)
  );
  NAND _1236_ (
    .A(_0245_),
    .B(_0481_),
    .Y(_0485_)
  );
  NAND _1237_ (
    .A(_0714_),
    .B(_0485_),
    .Y(_0486_)
  );
  NOR _1238_ (
    .A(_0484_),
    .B(_0486_),
    .Y(_0046_)
  );
  NAND _1239_ (
    .A(_0139_),
    .B(_0484_),
    .Y(_0487_)
  );
  NOT _1240_ (
    .A(_0487_),
    .Y(_0488_)
  );
  NOR _1241_ (
    .A(_0139_),
    .B(_0484_),
    .Y(_0489_)
  );
  NOT _1242_ (
    .A(_0489_),
    .Y(_0490_)
  );
  NAND _1243_ (
    .A(_0714_),
    .B(_0490_),
    .Y(_0491_)
  );
  NOR _1244_ (
    .A(_0488_),
    .B(_0491_),
    .Y(_0048_)
  );
  NOR _1245_ (
    .A(_0246_),
    .B(_0487_),
    .Y(_0492_)
  );
  NAND _1246_ (
    .A(_0246_),
    .B(_0487_),
    .Y(_0493_)
  );
  NAND _1247_ (
    .A(_0714_),
    .B(_0493_),
    .Y(_0494_)
  );
  NOR _1248_ (
    .A(_0492_),
    .B(_0494_),
    .Y(_0049_)
  );
  NOR _1249_ (
    .A(_0099_),
    .B(_0327_),
    .Y(_0495_)
  );
  NOR _1250_ (
    .A(_0248_),
    .B(_0495_),
    .Y(_0008_)
  );
  NAND _1251_ (
    .A(_0148_),
    .B(_0340_),
    .Y(_0496_)
  );
  NOT _1252_ (
    .A(_0496_),
    .Y(_0497_)
  );
  NAND _1253_ (
    .A(_0188_),
    .B(_0339_),
    .Y(_0498_)
  );
  NAND _1254_ (
    .A(_0714_),
    .B(_0498_),
    .Y(_0499_)
  );
  NOR _1255_ (
    .A(_0497_),
    .B(_0499_),
    .Y(_0057_)
  );
  NAND _1256_ (
    .A(_0189_),
    .B(_0496_),
    .Y(_0500_)
  );
  NAND _1257_ (
    .A(_0148_),
    .B(_0159_),
    .Y(_0501_)
  );
  NOT _1258_ (
    .A(_0501_),
    .Y(_0502_)
  );
  NOR _1259_ (
    .A(_0339_),
    .B(_0501_),
    .Y(_0503_)
  );
  NAND _1260_ (
    .A(_0714_),
    .B(_0500_),
    .Y(_0504_)
  );
  NOR _1261_ (
    .A(_0189_),
    .B(_0496_),
    .Y(_0505_)
  );
  NOT _1262_ (
    .A(_0505_),
    .Y(_0506_)
  );
  NOR _1263_ (
    .A(_0504_),
    .B(_0505_),
    .Y(_0068_)
  );
  NAND _1264_ (
    .A(_0170_),
    .B(_0503_),
    .Y(_0507_)
  );
  NOT _1265_ (
    .A(_0507_),
    .Y(_0508_)
  );
  NAND _1266_ (
    .A(_0111_),
    .B(_0112_),
    .Y(_0509_)
  );
  NAND _1267_ (
    .A(_0113_),
    .B(_0115_),
    .Y(_0510_)
  );
  NOR _1268_ (
    .A(_0509_),
    .B(_0510_),
    .Y(_0511_)
  );
  NAND _1269_ (
    .A(_0214_),
    .B(_0110_),
    .Y(_0512_)
  );
  NOR _1270_ (
    .A(_0109_),
    .B(_0114_),
    .Y(_0513_)
  );
  NAND _1271_ (
    .A(_0511_),
    .B(_0513_),
    .Y(_0514_)
  );
  NOR _1272_ (
    .A(_0512_),
    .B(_0514_),
    .Y(_0515_)
  );
  NOR _1273_ (
    .A(_0262_),
    .B(_0515_),
    .Y(_0516_)
  );
  NAND _1274_ (
    .A(_0327_),
    .B(_0516_),
    .Y(_0517_)
  );
  NAND _1275_ (
    .A(_0170_),
    .B(_0517_),
    .Y(_0518_)
  );
  NAND _1276_ (
    .A(_0339_),
    .B(_0518_),
    .Y(_0519_)
  );
  NOR _1277_ (
    .A(_0170_),
    .B(_0502_),
    .Y(_0520_)
  );
  NOR _1278_ (
    .A(_0248_),
    .B(_0520_),
    .Y(_0521_)
  );
  NAND _1279_ (
    .A(_0519_),
    .B(_0521_),
    .Y(_0522_)
  );
  NOR _1280_ (
    .A(_0508_),
    .B(_0522_),
    .Y(_0079_)
  );
  NAND _1281_ (
    .A(_0190_),
    .B(_0507_),
    .Y(_0523_)
  );
  NAND _1282_ (
    .A(_0714_),
    .B(_0523_),
    .Y(_0524_)
  );
  NAND _1283_ (
    .A(_0173_),
    .B(_0508_),
    .Y(_0525_)
  );
  NOT _1284_ (
    .A(_0525_),
    .Y(_0526_)
  );
  NOR _1285_ (
    .A(_0524_),
    .B(_0526_),
    .Y(_0082_)
  );
  NAND _1286_ (
    .A(_0191_),
    .B(_0525_),
    .Y(_0527_)
  );
  NAND _1287_ (
    .A(_0714_),
    .B(_0527_),
    .Y(_0528_)
  );
  NOR _1288_ (
    .A(_0191_),
    .B(_0525_),
    .Y(_0529_)
  );
  NAND _1289_ (
    .A(_0173_),
    .B(_0174_),
    .Y(_0530_)
  );
  NOR _1290_ (
    .A(_0528_),
    .B(_0529_),
    .Y(_0083_)
  );
  NOR _1291_ (
    .A(_0175_),
    .B(_0529_),
    .Y(_0531_)
  );
  NAND _1292_ (
    .A(_0174_),
    .B(_0175_),
    .Y(_0532_)
  );
  NOR _1293_ (
    .A(_0525_),
    .B(_0532_),
    .Y(_0533_)
  );
  NOT _1294_ (
    .A(_0533_),
    .Y(_0534_)
  );
  NAND _1295_ (
    .A(_0714_),
    .B(_0534_),
    .Y(_0535_)
  );
  NOR _1296_ (
    .A(_0192_),
    .B(_0530_),
    .Y(_0536_)
  );
  NAND _1297_ (
    .A(_0170_),
    .B(_0536_),
    .Y(_0537_)
  );
  NOR _1298_ (
    .A(_0506_),
    .B(_0537_),
    .Y(_0538_)
  );
  NOT _1299_ (
    .A(_0538_),
    .Y(_0539_)
  );
  NOR _1300_ (
    .A(_0531_),
    .B(_0535_),
    .Y(_0084_)
  );
  NAND _1301_ (
    .A(_0173_),
    .B(_0170_),
    .Y(_0540_)
  );
  NOT _1302_ (
    .A(_0540_),
    .Y(_0541_)
  );
  NOR _1303_ (
    .A(_0501_),
    .B(_0532_),
    .Y(_0542_)
  );
  NAND _1304_ (
    .A(_0541_),
    .B(_0542_),
    .Y(_0543_)
  );
  NOR _1305_ (
    .A(_0339_),
    .B(_0543_),
    .Y(_0544_)
  );
  NOR _1306_ (
    .A(_0176_),
    .B(_0544_),
    .Y(_0545_)
  );
  NOT _1307_ (
    .A(_0545_),
    .Y(_0546_)
  );
  NAND _1308_ (
    .A(_0714_),
    .B(_0546_),
    .Y(_0547_)
  );
  NOR _1309_ (
    .A(_0193_),
    .B(_0534_),
    .Y(_0548_)
  );
  NAND _1310_ (
    .A(_0176_),
    .B(_0533_),
    .Y(_0549_)
  );
  NOR _1311_ (
    .A(_0547_),
    .B(_0548_),
    .Y(_0085_)
  );
  NAND _1312_ (
    .A(_0194_),
    .B(_0549_),
    .Y(_0550_)
  );
  NAND _1313_ (
    .A(_0714_),
    .B(_0550_),
    .Y(_0551_)
  );
  NOR _1314_ (
    .A(_0194_),
    .B(_0549_),
    .Y(_0552_)
  );
  NAND _1315_ (
    .A(_0177_),
    .B(_0548_),
    .Y(_0553_)
  );
  NAND _1316_ (
    .A(_0176_),
    .B(_0177_),
    .Y(_0554_)
  );
  NOR _1317_ (
    .A(_0539_),
    .B(_0554_),
    .Y(_0555_)
  );
  NOR _1318_ (
    .A(_0551_),
    .B(_0552_),
    .Y(_0086_)
  );
  NAND _1319_ (
    .A(_0195_),
    .B(_0553_),
    .Y(_0556_)
  );
  NAND _1320_ (
    .A(_0714_),
    .B(_0556_),
    .Y(_0557_)
  );
  NAND _1321_ (
    .A(_0178_),
    .B(_0552_),
    .Y(_0558_)
  );
  NOT _1322_ (
    .A(_0558_),
    .Y(_0559_)
  );
  NAND _1323_ (
    .A(_0178_),
    .B(_0555_),
    .Y(_0560_)
  );
  NOR _1324_ (
    .A(_0557_),
    .B(_0559_),
    .Y(_0087_)
  );
  NOR _1325_ (
    .A(_0195_),
    .B(_0554_),
    .Y(_0561_)
  );
  NAND _1326_ (
    .A(_0196_),
    .B(_0558_),
    .Y(_0562_)
  );
  NAND _1327_ (
    .A(_0714_),
    .B(_0562_),
    .Y(_0563_)
  );
  NOR _1328_ (
    .A(_0196_),
    .B(_0558_),
    .Y(_0564_)
  );
  NOR _1329_ (
    .A(_0563_),
    .B(_0564_),
    .Y(_0088_)
  );
  NOR _1330_ (
    .A(_0149_),
    .B(_0564_),
    .Y(_0565_)
  );
  NAND _1331_ (
    .A(_0179_),
    .B(_0149_),
    .Y(_0566_)
  );
  NOR _1332_ (
    .A(_0558_),
    .B(_0566_),
    .Y(_0567_)
  );
  NOT _1333_ (
    .A(_0567_),
    .Y(_0568_)
  );
  NAND _1334_ (
    .A(_0714_),
    .B(_0568_),
    .Y(_0569_)
  );
  NOR _1335_ (
    .A(_0565_),
    .B(_0569_),
    .Y(_0058_)
  );
  NOR _1336_ (
    .A(_0150_),
    .B(_0567_),
    .Y(_0570_)
  );
  NOT _1337_ (
    .A(_0570_),
    .Y(_0571_)
  );
  NAND _1338_ (
    .A(_0714_),
    .B(_0571_),
    .Y(_0572_)
  );
  NAND _1339_ (
    .A(_0150_),
    .B(_0567_),
    .Y(_0573_)
  );
  NOR _1340_ (
    .A(_0197_),
    .B(_0566_),
    .Y(_0574_)
  );
  NOT _1341_ (
    .A(_0574_),
    .Y(_0575_)
  );
  NOR _1342_ (
    .A(_0560_),
    .B(_0575_),
    .Y(_0576_)
  );
  NOR _1343_ (
    .A(_0572_),
    .B(_0576_),
    .Y(_0059_)
  );
  NAND _1344_ (
    .A(_0561_),
    .B(_0574_),
    .Y(_0577_)
  );
  NOT _1345_ (
    .A(_0577_),
    .Y(_0578_)
  );
  NAND _1346_ (
    .A(_0544_),
    .B(_0578_),
    .Y(_0579_)
  );
  NAND _1347_ (
    .A(_0198_),
    .B(_0579_),
    .Y(_0580_)
  );
  NAND _1348_ (
    .A(_0714_),
    .B(_0580_),
    .Y(_0581_)
  );
  NOR _1349_ (
    .A(_0198_),
    .B(_0573_),
    .Y(_0582_)
  );
  NAND _1350_ (
    .A(_0151_),
    .B(_0576_),
    .Y(_0583_)
  );
  NOR _1351_ (
    .A(_0581_),
    .B(_0582_),
    .Y(_0060_)
  );
  NOR _1352_ (
    .A(_0152_),
    .B(_0582_),
    .Y(_0584_)
  );
  NAND _1353_ (
    .A(_0151_),
    .B(_0152_),
    .Y(_0585_)
  );
  NOR _1354_ (
    .A(_0573_),
    .B(_0585_),
    .Y(_0586_)
  );
  NOT _1355_ (
    .A(_0586_),
    .Y(_0587_)
  );
  NAND _1356_ (
    .A(_0714_),
    .B(_0587_),
    .Y(_0588_)
  );
  NOR _1357_ (
    .A(_0199_),
    .B(_0583_),
    .Y(_0589_)
  );
  NOR _1358_ (
    .A(_0579_),
    .B(_0585_),
    .Y(_0590_)
  );
  NOR _1359_ (
    .A(_0584_),
    .B(_0588_),
    .Y(_0061_)
  );
  NOR _1360_ (
    .A(_0153_),
    .B(_0590_),
    .Y(_0591_)
  );
  NOT _1361_ (
    .A(_0591_),
    .Y(_0592_)
  );
  NAND _1362_ (
    .A(_0714_),
    .B(_0592_),
    .Y(_0593_)
  );
  NAND _1363_ (
    .A(_0153_),
    .B(_0586_),
    .Y(_0594_)
  );
  NOT _1364_ (
    .A(_0594_),
    .Y(_0595_)
  );
  NAND _1365_ (
    .A(_0153_),
    .B(_0589_),
    .Y(_0596_)
  );
  NAND _1366_ (
    .A(_0153_),
    .B(_0590_),
    .Y(_0597_)
  );
  NOR _1367_ (
    .A(_0593_),
    .B(_0595_),
    .Y(_0062_)
  );
  NAND _1368_ (
    .A(_0200_),
    .B(_0597_),
    .Y(_0598_)
  );
  NAND _1369_ (
    .A(_0714_),
    .B(_0598_),
    .Y(_0599_)
  );
  NOR _1370_ (
    .A(_0200_),
    .B(_0597_),
    .Y(_0600_)
  );
  NOR _1371_ (
    .A(_0599_),
    .B(_0600_),
    .Y(_0063_)
  );
  NOR _1372_ (
    .A(_0155_),
    .B(_0600_),
    .Y(_0601_)
  );
  NOT _1373_ (
    .A(_0601_),
    .Y(_0602_)
  );
  NAND _1374_ (
    .A(_0714_),
    .B(_0602_),
    .Y(_0603_)
  );
  NAND _1375_ (
    .A(_0154_),
    .B(_0155_),
    .Y(_0604_)
  );
  NOT _1376_ (
    .A(_0604_),
    .Y(_0605_)
  );
  NOR _1377_ (
    .A(_0596_),
    .B(_0604_),
    .Y(_0606_)
  );
  NAND _1378_ (
    .A(_0155_),
    .B(_0600_),
    .Y(_0607_)
  );
  NOR _1379_ (
    .A(_0603_),
    .B(_0606_),
    .Y(_0064_)
  );
  NAND _1380_ (
    .A(_0201_),
    .B(_0607_),
    .Y(_0608_)
  );
  NAND _1381_ (
    .A(_0714_),
    .B(_0608_),
    .Y(_0609_)
  );
  NAND _1382_ (
    .A(_0156_),
    .B(_0606_),
    .Y(_0610_)
  );
  NOT _1383_ (
    .A(_0610_),
    .Y(_0611_)
  );
  NOR _1384_ (
    .A(_0609_),
    .B(_0611_),
    .Y(_0065_)
  );
  NAND _1385_ (
    .A(_0156_),
    .B(_0605_),
    .Y(_0612_)
  );
  NAND _1386_ (
    .A(_0202_),
    .B(_0610_),
    .Y(_0613_)
  );
  NAND _1387_ (
    .A(_0714_),
    .B(_0613_),
    .Y(_0614_)
  );
  NOR _1388_ (
    .A(_0202_),
    .B(_0610_),
    .Y(_0615_)
  );
  NAND _1389_ (
    .A(_0157_),
    .B(_0611_),
    .Y(_0616_)
  );
  NOR _1390_ (
    .A(_0614_),
    .B(_0615_),
    .Y(_0066_)
  );
  NAND _1391_ (
    .A(_0153_),
    .B(_0157_),
    .Y(_0617_)
  );
  NOR _1392_ (
    .A(_0585_),
    .B(_0617_),
    .Y(_0618_)
  );
  NAND _1393_ (
    .A(_0158_),
    .B(_0618_),
    .Y(_0619_)
  );
  NOR _1394_ (
    .A(_0612_),
    .B(_0619_),
    .Y(_0620_)
  );
  NOR _1395_ (
    .A(_0203_),
    .B(_0616_),
    .Y(_0621_)
  );
  NAND _1396_ (
    .A(_0576_),
    .B(_0620_),
    .Y(_0622_)
  );
  NAND _1397_ (
    .A(_0203_),
    .B(_0616_),
    .Y(_0623_)
  );
  NAND _1398_ (
    .A(_0714_),
    .B(_0623_),
    .Y(_0624_)
  );
  NOR _1399_ (
    .A(_0621_),
    .B(_0624_),
    .Y(_0067_)
  );
  NAND _1400_ (
    .A(_0204_),
    .B(_0622_),
    .Y(_0625_)
  );
  NAND _1401_ (
    .A(_0714_),
    .B(_0625_),
    .Y(_0626_)
  );
  NOR _1402_ (
    .A(_0204_),
    .B(_0622_),
    .Y(_0627_)
  );
  NAND _1403_ (
    .A(_0160_),
    .B(_0621_),
    .Y(_0628_)
  );
  NAND _1404_ (
    .A(_0160_),
    .B(_0620_),
    .Y(_0629_)
  );
  NOR _1405_ (
    .A(_0626_),
    .B(_0627_),
    .Y(_0069_)
  );
  NAND _1406_ (
    .A(_0205_),
    .B(_0628_),
    .Y(_0630_)
  );
  NAND _1407_ (
    .A(_0714_),
    .B(_0630_),
    .Y(_0631_)
  );
  NOR _1408_ (
    .A(_0205_),
    .B(_0628_),
    .Y(_0632_)
  );
  NAND _1409_ (
    .A(_0161_),
    .B(_0627_),
    .Y(_0633_)
  );
  NOR _1410_ (
    .A(_0631_),
    .B(_0632_),
    .Y(_0070_)
  );
  NAND _1411_ (
    .A(_0206_),
    .B(_0633_),
    .Y(_0634_)
  );
  NAND _1412_ (
    .A(_0714_),
    .B(_0634_),
    .Y(_0635_)
  );
  NAND _1413_ (
    .A(_0161_),
    .B(_0162_),
    .Y(_0636_)
  );
  NOT _1414_ (
    .A(_0636_),
    .Y(_0637_)
  );
  NOR _1415_ (
    .A(_0628_),
    .B(_0636_),
    .Y(_0638_)
  );
  NAND _1416_ (
    .A(_0627_),
    .B(_0637_),
    .Y(_0639_)
  );
  NOR _1417_ (
    .A(_0635_),
    .B(_0638_),
    .Y(_0071_)
  );
  NOR _1418_ (
    .A(_0207_),
    .B(_0501_),
    .Y(_0640_)
  );
  NAND _1419_ (
    .A(_0637_),
    .B(_0640_),
    .Y(_0641_)
  );
  NOR _1420_ (
    .A(_0537_),
    .B(_0641_),
    .Y(_0642_)
  );
  NAND _1421_ (
    .A(_0578_),
    .B(_0642_),
    .Y(_0643_)
  );
  NOR _1422_ (
    .A(_0629_),
    .B(_0643_),
    .Y(_0644_)
  );
  NOR _1423_ (
    .A(_0207_),
    .B(_0639_),
    .Y(_0645_)
  );
  NAND _1424_ (
    .A(_0340_),
    .B(_0644_),
    .Y(_0646_)
  );
  NOR _1425_ (
    .A(_0163_),
    .B(_0638_),
    .Y(_0647_)
  );
  NOR _1426_ (
    .A(_0248_),
    .B(_0647_),
    .Y(_0648_)
  );
  NAND _1427_ (
    .A(_0646_),
    .B(_0648_),
    .Y(_0649_)
  );
  NOT _1428_ (
    .A(_0649_),
    .Y(_0072_)
  );
  NOR _1429_ (
    .A(_0208_),
    .B(_0646_),
    .Y(_0650_)
  );
  NAND _1430_ (
    .A(_0208_),
    .B(_0646_),
    .Y(_0651_)
  );
  NAND _1431_ (
    .A(_0714_),
    .B(_0651_),
    .Y(_0652_)
  );
  NOR _1432_ (
    .A(_0650_),
    .B(_0652_),
    .Y(_0073_)
  );
  NOR _1433_ (
    .A(_0165_),
    .B(_0650_),
    .Y(_0653_)
  );
  NAND _1434_ (
    .A(_0164_),
    .B(_0165_),
    .Y(_0654_)
  );
  NOT _1435_ (
    .A(_0654_),
    .Y(_0655_)
  );
  NOR _1436_ (
    .A(_0646_),
    .B(_0654_),
    .Y(_0656_)
  );
  NAND _1437_ (
    .A(_0645_),
    .B(_0655_),
    .Y(_0657_)
  );
  NAND _1438_ (
    .A(_0714_),
    .B(_0657_),
    .Y(_0658_)
  );
  NOR _1439_ (
    .A(_0653_),
    .B(_0658_),
    .Y(_0074_)
  );
  NAND _1440_ (
    .A(_0209_),
    .B(_0657_),
    .Y(_0659_)
  );
  NAND _1441_ (
    .A(_0714_),
    .B(_0659_),
    .Y(_0660_)
  );
  NOR _1442_ (
    .A(_0209_),
    .B(_0657_),
    .Y(_0661_)
  );
  NAND _1443_ (
    .A(_0166_),
    .B(_0656_),
    .Y(_0662_)
  );
  NOR _1444_ (
    .A(_0660_),
    .B(_0661_),
    .Y(_0075_)
  );
  NAND _1445_ (
    .A(_0210_),
    .B(_0662_),
    .Y(_0663_)
  );
  NAND _1446_ (
    .A(_0714_),
    .B(_0663_),
    .Y(_0664_)
  );
  NOR _1447_ (
    .A(_0210_),
    .B(_0662_),
    .Y(_0665_)
  );
  NAND _1448_ (
    .A(_0167_),
    .B(_0661_),
    .Y(_0666_)
  );
  NAND _1449_ (
    .A(_0166_),
    .B(_0167_),
    .Y(_0667_)
  );
  NOR _1450_ (
    .A(_0664_),
    .B(_0665_),
    .Y(_0076_)
  );
  NAND _1451_ (
    .A(_0211_),
    .B(_0666_),
    .Y(_0668_)
  );
  NAND _1452_ (
    .A(_0714_),
    .B(_0668_),
    .Y(_0669_)
  );
  NOR _1453_ (
    .A(_0211_),
    .B(_0666_),
    .Y(_0670_)
  );
  NOR _1454_ (
    .A(_0669_),
    .B(_0670_),
    .Y(_0077_)
  );
  NOR _1455_ (
    .A(_0169_),
    .B(_0670_),
    .Y(_0671_)
  );
  NOR _1456_ (
    .A(_0211_),
    .B(_0667_),
    .Y(_0672_)
  );
  NAND _1457_ (
    .A(_0169_),
    .B(_0672_),
    .Y(_0673_)
  );
  NOR _1458_ (
    .A(_0654_),
    .B(_0673_),
    .Y(_0674_)
  );
  NAND _1459_ (
    .A(_0644_),
    .B(_0674_),
    .Y(_0675_)
  );
  NAND _1460_ (
    .A(_0645_),
    .B(_0674_),
    .Y(_0676_)
  );
  NAND _1461_ (
    .A(_0714_),
    .B(_0676_),
    .Y(_0677_)
  );
  NOR _1462_ (
    .A(_0671_),
    .B(_0677_),
    .Y(_0078_)
  );
  NOR _1463_ (
    .A(_0212_),
    .B(_0676_),
    .Y(_0678_)
  );
  NAND _1464_ (
    .A(_0212_),
    .B(_0676_),
    .Y(_0679_)
  );
  NAND _1465_ (
    .A(_0714_),
    .B(_0679_),
    .Y(_0680_)
  );
  NOR _1466_ (
    .A(_0678_),
    .B(_0680_),
    .Y(_0080_)
  );
  NAND _1467_ (
    .A(_0171_),
    .B(_0261_),
    .Y(_0681_)
  );
  NOR _1468_ (
    .A(_0675_),
    .B(_0681_),
    .Y(_0682_)
  );
  NOR _1469_ (
    .A(_0172_),
    .B(_0682_),
    .Y(_0683_)
  );
  NOT _1470_ (
    .A(_0683_),
    .Y(_0684_)
  );
  NAND _1471_ (
    .A(_0714_),
    .B(_0684_),
    .Y(_0685_)
  );
  NOR _1472_ (
    .A(_0682_),
    .B(_0685_),
    .Y(_0081_)
  );
  NOR _1473_ (
    .A(_0248_),
    .B(_0293_),
    .Y(_0686_)
  );
  NAND _1474_ (
    .A(_0714_),
    .B(_0294_),
    .Y(_0687_)
  );
  NOR _1475_ (
    .A(_0100_),
    .B(_0687_),
    .Y(_0688_)
  );
  NOR _1476_ (
    .A(_0108_),
    .B(_0686_),
    .Y(_0689_)
  );
  NOR _1477_ (
    .A(_0688_),
    .B(_0689_),
    .Y(_0017_)
  );
  NOR _1478_ (
    .A(_0101_),
    .B(_0687_),
    .Y(_0690_)
  );
  NOR _1479_ (
    .A(_0109_),
    .B(_0686_),
    .Y(_0691_)
  );
  NOR _1480_ (
    .A(_0690_),
    .B(_0691_),
    .Y(_0018_)
  );
  NOR _1481_ (
    .A(_0102_),
    .B(_0687_),
    .Y(_0692_)
  );
  NOR _1482_ (
    .A(_0110_),
    .B(_0686_),
    .Y(_0693_)
  );
  NOR _1483_ (
    .A(_0692_),
    .B(_0693_),
    .Y(_0019_)
  );
  NOR _1484_ (
    .A(_0103_),
    .B(_0687_),
    .Y(_0694_)
  );
  NOR _1485_ (
    .A(_0111_),
    .B(_0686_),
    .Y(_0695_)
  );
  NOR _1486_ (
    .A(_0694_),
    .B(_0695_),
    .Y(_0020_)
  );
  NOR _1487_ (
    .A(_0104_),
    .B(_0687_),
    .Y(_0696_)
  );
  NOR _1488_ (
    .A(_0112_),
    .B(_0686_),
    .Y(_0697_)
  );
  NOR _1489_ (
    .A(_0696_),
    .B(_0697_),
    .Y(_0021_)
  );
  NOR _1490_ (
    .A(_0105_),
    .B(_0687_),
    .Y(_0698_)
  );
  NOR _1491_ (
    .A(_0113_),
    .B(_0686_),
    .Y(_0699_)
  );
  NOR _1492_ (
    .A(_0698_),
    .B(_0699_),
    .Y(_0022_)
  );
  NOR _1493_ (
    .A(_0106_),
    .B(_0687_),
    .Y(_0700_)
  );
  NOR _1494_ (
    .A(_0114_),
    .B(_0686_),
    .Y(_0701_)
  );
  NOR _1495_ (
    .A(_0700_),
    .B(_0701_),
    .Y(_0023_)
  );
  NAND _1496_ (
    .A(_0107_),
    .B(_0686_),
    .Y(_0702_)
  );
  NAND _1497_ (
    .A(_0115_),
    .B(_0687_),
    .Y(_0703_)
  );
  NAND _1498_ (
    .A(_0702_),
    .B(_0703_),
    .Y(_0024_)
  );
  NAND _1499_ (
    .A(_0714_),
    .B(_0098_),
    .Y(_0704_)
  );
  NOT _1500_ (
    .A(_0704_),
    .Y(_0009_)
  );
  NAND _1501_ (
    .A(_0100_),
    .B(_0714_),
    .Y(_0705_)
  );
  NOT _1502_ (
    .A(_0705_),
    .Y(_0010_)
  );
  NAND _1503_ (
    .A(_0101_),
    .B(_0714_),
    .Y(_0706_)
  );
  NOT _1504_ (
    .A(_0706_),
    .Y(_0011_)
  );
  NAND _1505_ (
    .A(_0714_),
    .B(_0102_),
    .Y(_0707_)
  );
  NOT _1506_ (
    .A(_0707_),
    .Y(_0012_)
  );
  NAND _1507_ (
    .A(_0714_),
    .B(_0103_),
    .Y(_0708_)
  );
  NOT _1508_ (
    .A(_0708_),
    .Y(_0013_)
  );
  NAND _1509_ (
    .A(_0714_),
    .B(_0104_),
    .Y(_0709_)
  );
  NOT _1510_ (
    .A(_0709_),
    .Y(_0014_)
  );
  NAND _1511_ (
    .A(_0714_),
    .B(_0105_),
    .Y(_0710_)
  );
  NOT _1512_ (
    .A(_0710_),
    .Y(_0015_)
  );
  NAND _1513_ (
    .A(_0106_),
    .B(_0714_),
    .Y(_0711_)
  );
  NOT _1514_ (
    .A(_0711_),
    .Y(_0016_)
  );
  NOR _1515_ (
    .A(_0097_),
    .B(_0332_),
    .Y(_0712_)
  );
  NAND _1516_ (
    .A(_0341_),
    .B(_0517_),
    .Y(_0713_)
  );
  NOR _1517_ (
    .A(_0712_),
    .B(_0713_),
    .Y(_0007_)
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1518_ (
    .C(clk_32f),
    .D(_0000_),
    .Q(IDLEOut_sintetizado)
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1519_ (
    .C(clk_32f),
    .D(_0002_[0]),
    .Q(buffer[0])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1520_ (
    .C(clk_32f),
    .D(_0002_[1]),
    .Q(buffer[1])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1521_ (
    .C(clk_32f),
    .D(_0002_[2]),
    .Q(buffer[2])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1522_ (
    .C(clk_32f),
    .D(_0002_[3]),
    .Q(buffer[3])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1523_ (
    .C(clk_32f),
    .D(_0002_[4]),
    .Q(buffer[4])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1524_ (
    .C(clk_32f),
    .D(_0002_[5]),
    .Q(buffer[5])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1525_ (
    .C(clk_32f),
    .D(_0002_[6]),
    .Q(buffer[6])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1526_ (
    .C(clk_32f),
    .D(_0002_[7]),
    .Q(buffer[7])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1527_ (
    .C(clk_32f),
    .D(_0003_[0]),
    .Q(buffer_pasado[0])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1528_ (
    .C(clk_32f),
    .D(_0003_[1]),
    .Q(buffer_pasado[1])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1529_ (
    .C(clk_32f),
    .D(_0003_[2]),
    .Q(buffer_pasado[2])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1530_ (
    .C(clk_32f),
    .D(_0003_[3]),
    .Q(buffer_pasado[3])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1531_ (
    .C(clk_32f),
    .D(_0003_[4]),
    .Q(buffer_pasado[4])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1532_ (
    .C(clk_32f),
    .D(_0003_[5]),
    .Q(buffer_pasado[5])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1533_ (
    .C(clk_32f),
    .D(_0003_[6]),
    .Q(buffer_pasado[6])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1534_ (
    .C(clk_32f),
    .D(_0003_[7]),
    .Q(buffer_pasado[7])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1535_ (
    .C(clk_32f),
    .D(_0006_[0]),
    .Q(data_serial_paraleloTX_sintetizado[0])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1536_ (
    .C(clk_32f),
    .D(_0006_[1]),
    .Q(data_serial_paraleloTX_sintetizado[1])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1537_ (
    .C(clk_32f),
    .D(_0006_[2]),
    .Q(data_serial_paraleloTX_sintetizado[2])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1538_ (
    .C(clk_32f),
    .D(_0006_[3]),
    .Q(data_serial_paraleloTX_sintetizado[3])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1539_ (
    .C(clk_32f),
    .D(_0006_[4]),
    .Q(data_serial_paraleloTX_sintetizado[4])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1540_ (
    .C(clk_32f),
    .D(_0006_[5]),
    .Q(data_serial_paraleloTX_sintetizado[5])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1541_ (
    .C(clk_32f),
    .D(_0006_[6]),
    .Q(data_serial_paraleloTX_sintetizado[6])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1542_ (
    .C(clk_32f),
    .D(_0006_[7]),
    .Q(data_serial_paraleloTX_sintetizado[7])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1543_ (
    .C(clk_32f),
    .D(_0001_),
    .Q(active_serial_paraleloTX_sintetizado)
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1544_ (
    .C(clk_32f),
    .D(_0004_[0]),
    .Q(contador[0])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1545_ (
    .C(clk_32f),
    .D(_0004_[1]),
    .Q(contador[1])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1546_ (
    .C(clk_32f),
    .D(_0004_[2]),
    .Q(contador[2])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1547_ (
    .C(clk_32f),
    .D(_0004_[3]),
    .Q(contador[3])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1548_ (
    .C(clk_32f),
    .D(_0004_[4]),
    .Q(contador[4])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1549_ (
    .C(clk_32f),
    .D(_0004_[5]),
    .Q(contador[5])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1550_ (
    .C(clk_32f),
    .D(_0004_[6]),
    .Q(contador[6])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1551_ (
    .C(clk_32f),
    .D(_0004_[7]),
    .Q(contador[7])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1552_ (
    .C(clk_32f),
    .D(_0004_[8]),
    .Q(contador[8])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1553_ (
    .C(clk_32f),
    .D(_0004_[9]),
    .Q(contador[9])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1554_ (
    .C(clk_32f),
    .D(_0004_[10]),
    .Q(contador[10])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1555_ (
    .C(clk_32f),
    .D(_0004_[11]),
    .Q(contador[11])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1556_ (
    .C(clk_32f),
    .D(_0004_[12]),
    .Q(contador[12])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1557_ (
    .C(clk_32f),
    .D(_0004_[13]),
    .Q(contador[13])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1558_ (
    .C(clk_32f),
    .D(_0004_[14]),
    .Q(contador[14])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1559_ (
    .C(clk_32f),
    .D(_0004_[15]),
    .Q(contador[15])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1560_ (
    .C(clk_32f),
    .D(_0004_[16]),
    .Q(contador[16])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1561_ (
    .C(clk_32f),
    .D(_0004_[17]),
    .Q(contador[17])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1562_ (
    .C(clk_32f),
    .D(_0004_[18]),
    .Q(contador[18])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1563_ (
    .C(clk_32f),
    .D(_0004_[19]),
    .Q(contador[19])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1564_ (
    .C(clk_32f),
    .D(_0004_[20]),
    .Q(contador[20])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1565_ (
    .C(clk_32f),
    .D(_0004_[21]),
    .Q(contador[21])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1566_ (
    .C(clk_32f),
    .D(_0004_[22]),
    .Q(contador[22])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1567_ (
    .C(clk_32f),
    .D(_0004_[23]),
    .Q(contador[23])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1568_ (
    .C(clk_32f),
    .D(_0004_[24]),
    .Q(contador[24])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1569_ (
    .C(clk_32f),
    .D(_0004_[25]),
    .Q(contador[25])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1570_ (
    .C(clk_32f),
    .D(_0004_[26]),
    .Q(contador[26])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1571_ (
    .C(clk_32f),
    .D(_0004_[27]),
    .Q(contador[27])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1572_ (
    .C(clk_32f),
    .D(_0004_[28]),
    .Q(contador[28])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1573_ (
    .C(clk_32f),
    .D(_0004_[29]),
    .Q(contador[29])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1574_ (
    .C(clk_32f),
    .D(_0004_[30]),
    .Q(contador[30])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1575_ (
    .C(clk_32f),
    .D(_0004_[31]),
    .Q(contador[31])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1576_ (
    .C(clk_32f),
    .D(_0005_[0]),
    .Q(contador_BC[0])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1577_ (
    .C(clk_32f),
    .D(_0005_[1]),
    .Q(contador_BC[1])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1578_ (
    .C(clk_32f),
    .D(_0005_[2]),
    .Q(contador_BC[2])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1579_ (
    .C(clk_32f),
    .D(_0005_[3]),
    .Q(contador_BC[3])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1580_ (
    .C(clk_32f),
    .D(_0005_[4]),
    .Q(contador_BC[4])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1581_ (
    .C(clk_32f),
    .D(_0005_[5]),
    .Q(contador_BC[5])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1582_ (
    .C(clk_32f),
    .D(_0005_[6]),
    .Q(contador_BC[6])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1583_ (
    .C(clk_32f),
    .D(_0005_[7]),
    .Q(contador_BC[7])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1584_ (
    .C(clk_32f),
    .D(_0005_[8]),
    .Q(contador_BC[8])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1585_ (
    .C(clk_32f),
    .D(_0005_[9]),
    .Q(contador_BC[9])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1586_ (
    .C(clk_32f),
    .D(_0005_[10]),
    .Q(contador_BC[10])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1587_ (
    .C(clk_32f),
    .D(_0005_[11]),
    .Q(contador_BC[11])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1588_ (
    .C(clk_32f),
    .D(_0005_[12]),
    .Q(contador_BC[12])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1589_ (
    .C(clk_32f),
    .D(_0005_[13]),
    .Q(contador_BC[13])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1590_ (
    .C(clk_32f),
    .D(_0005_[14]),
    .Q(contador_BC[14])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1591_ (
    .C(clk_32f),
    .D(_0005_[15]),
    .Q(contador_BC[15])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1592_ (
    .C(clk_32f),
    .D(_0005_[16]),
    .Q(contador_BC[16])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1593_ (
    .C(clk_32f),
    .D(_0005_[17]),
    .Q(contador_BC[17])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1594_ (
    .C(clk_32f),
    .D(_0005_[18]),
    .Q(contador_BC[18])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1595_ (
    .C(clk_32f),
    .D(_0005_[19]),
    .Q(contador_BC[19])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1596_ (
    .C(clk_32f),
    .D(_0005_[20]),
    .Q(contador_BC[20])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1597_ (
    .C(clk_32f),
    .D(_0005_[21]),
    .Q(contador_BC[21])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1598_ (
    .C(clk_32f),
    .D(_0005_[22]),
    .Q(contador_BC[22])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1599_ (
    .C(clk_32f),
    .D(_0005_[23]),
    .Q(contador_BC[23])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1600_ (
    .C(clk_32f),
    .D(_0005_[24]),
    .Q(contador_BC[24])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1601_ (
    .C(clk_32f),
    .D(_0005_[25]),
    .Q(contador_BC[25])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1602_ (
    .C(clk_32f),
    .D(_0005_[26]),
    .Q(contador_BC[26])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1603_ (
    .C(clk_32f),
    .D(_0005_[27]),
    .Q(contador_BC[27])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1604_ (
    .C(clk_32f),
    .D(_0005_[28]),
    .Q(contador_BC[28])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1605_ (
    .C(clk_32f),
    .D(_0005_[29]),
    .Q(contador_BC[29])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1606_ (
    .C(clk_32f),
    .D(_0005_[30]),
    .Q(contador_BC[30])
  );
  (* src = "sintetizatx.v:21" *)
  DFF _1607_ (
    .C(clk_32f),
    .D(_0005_[31]),
    .Q(contador_BC[31])
  );
  assign _0729_[15:2] = _0725_[15:2];
  assign _0730_[7:1] = _0726_[7:1];
  assign _0731_[3:1] = _0727_[3:1];
  assign _0732_[1] = _0728_[1];
  assign { _0733_[31:3], _0733_[1:0] } = { contador_BC[31:3], contador_BC[1:0] };
  assign { _0734_[6], _0734_[1:0] } = { buffer[6], buffer[1:0] };
  assign { _0735_[6], _0735_[1:0] } = { buffer_pasado[6], buffer_pasado[1:0] };
  assign { _0736_[31:3], _0736_[0] } = { contador[31:3], _0716_[0] };
  assign _0767_[0] = contador_BC[0];
  assign _0768_[0] = contador[0];
  assign { _0771_[2], _0771_[0] } = { contador_BC[2], _0715_[0] };
  assign _0148_ = contador_BC[0];
  assign _0159_ = contador_BC[1];
  assign _0173_ = contador_BC[3];
  assign _0174_ = contador_BC[4];
  assign _0175_ = contador_BC[5];
  assign _0176_ = contador_BC[6];
  assign _0177_ = contador_BC[7];
  assign _0178_ = contador_BC[8];
  assign _0179_ = contador_BC[9];
  assign _0149_ = contador_BC[10];
  assign _0150_ = contador_BC[11];
  assign _0151_ = contador_BC[12];
  assign _0152_ = contador_BC[13];
  assign _0153_ = contador_BC[14];
  assign _0154_ = contador_BC[15];
  assign _0155_ = contador_BC[16];
  assign _0156_ = contador_BC[17];
  assign _0157_ = contador_BC[18];
  assign _0158_ = contador_BC[19];
  assign _0160_ = contador_BC[20];
  assign _0161_ = contador_BC[21];
  assign _0162_ = contador_BC[22];
  assign _0163_ = contador_BC[23];
  assign _0164_ = contador_BC[24];
  assign _0165_ = contador_BC[25];
  assign _0166_ = contador_BC[26];
  assign _0167_ = contador_BC[27];
  assign _0168_ = contador_BC[28];
  assign _0169_ = contador_BC[29];
  assign _0171_ = contador_BC[30];
  assign _0172_ = contador_BC[31];
  assign _0108_ = buffer_pasado[0];
  assign _0109_ = buffer_pasado[1];
  assign _0114_ = buffer_pasado[6];
  assign _0100_ = buffer[0];
  assign _0101_ = buffer[1];
  assign _0106_ = buffer[6];
  assign _0127_ = contador[1];
  assign _0138_ = contador[2];
  assign _0141_ = contador[3];
  assign _0142_ = contador[4];
  assign _0143_ = contador[5];
  assign _0144_ = contador[6];
  assign _0145_ = contador[7];
  assign _0146_ = contador[8];
  assign _0147_ = contador[9];
  assign _0117_ = contador[10];
  assign _0118_ = contador[11];
  assign _0119_ = contador[12];
  assign _0120_ = contador[13];
  assign _0121_ = contador[14];
  assign _0122_ = contador[15];
  assign _0123_ = contador[16];
  assign _0124_ = contador[17];
  assign _0125_ = contador[18];
  assign _0126_ = contador[19];
  assign _0128_ = contador[20];
  assign _0129_ = contador[21];
  assign _0130_ = contador[22];
  assign _0131_ = contador[23];
  assign _0132_ = contador[24];
  assign _0133_ = contador[25];
  assign _0134_ = contador[26];
  assign _0135_ = contador[27];
  assign _0136_ = contador[28];
  assign _0137_ = contador[29];
  assign _0139_ = contador[30];
  assign _0140_ = contador[31];
  assign _0187_ = data_serial_paraleloTX_sintetizado[7];
  assign _0107_ = buffer[7];
  assign _0714_ = reset;
  assign _0006_[7] = _0096_;
  assign _0180_ = data_serial_paraleloTX_sintetizado[0];
  assign _0181_ = data_serial_paraleloTX_sintetizado[1];
  assign _0182_ = data_serial_paraleloTX_sintetizado[2];
  assign _0102_ = buffer[2];
  assign _0183_ = data_serial_paraleloTX_sintetizado[3];
  assign _0103_ = buffer[3];
  assign _0184_ = data_serial_paraleloTX_sintetizado[4];
  assign _0104_ = buffer[4];
  assign _0185_ = data_serial_paraleloTX_sintetizado[5];
  assign _0105_ = buffer[5];
  assign _0186_ = data_serial_paraleloTX_sintetizado[6];
  assign _0006_[0] = _0089_;
  assign _0006_[1] = _0090_;
  assign _0006_[2] = _0091_;
  assign _0006_[3] = _0092_;
  assign _0006_[4] = _0093_;
  assign _0006_[5] = _0094_;
  assign _0006_[6] = _0095_;
  assign _0004_[0] = _0025_;
  assign _0004_[1] = _0036_;
  assign _0004_[2] = _0047_;
  assign _0004_[3] = _0050_;
  assign _0004_[4] = _0051_;
  assign _0004_[5] = _0052_;
  assign _0004_[6] = _0053_;
  assign _0004_[7] = _0054_;
  assign _0004_[8] = _0055_;
  assign _0004_[9] = _0056_;
  assign _0004_[10] = _0026_;
  assign _0004_[11] = _0027_;
  assign _0004_[12] = _0028_;
  assign _0004_[13] = _0029_;
  assign _0004_[14] = _0030_;
  assign _0004_[15] = _0031_;
  assign _0004_[16] = _0032_;
  assign _0004_[17] = _0033_;
  assign _0004_[18] = _0034_;
  assign _0004_[19] = _0035_;
  assign _0004_[20] = _0037_;
  assign _0004_[21] = _0038_;
  assign _0004_[22] = _0039_;
  assign _0004_[23] = _0040_;
  assign _0004_[24] = _0041_;
  assign _0004_[25] = _0042_;
  assign _0004_[26] = _0043_;
  assign _0004_[27] = _0044_;
  assign _0004_[28] = _0045_;
  assign _0004_[29] = _0046_;
  assign _0004_[30] = _0048_;
  assign _0004_[31] = _0049_;
  assign _0116_ = contador[0];
  assign _0170_ = contador_BC[2];
  assign _0099_ = active_serial_paraleloTX_sintetizado;
  assign _0001_ = _0008_;
  assign _0110_ = buffer_pasado[2];
  assign _0111_ = buffer_pasado[3];
  assign _0112_ = buffer_pasado[4];
  assign _0113_ = buffer_pasado[5];
  assign _0115_ = buffer_pasado[7];
  assign _0005_[0] = _0057_;
  assign _0005_[1] = _0068_;
  assign _0005_[2] = _0079_;
  assign _0005_[3] = _0082_;
  assign _0005_[4] = _0083_;
  assign _0005_[5] = _0084_;
  assign _0005_[6] = _0085_;
  assign _0005_[7] = _0086_;
  assign _0005_[8] = _0087_;
  assign _0005_[9] = _0088_;
  assign _0005_[10] = _0058_;
  assign _0005_[11] = _0059_;
  assign _0005_[12] = _0060_;
  assign _0005_[13] = _0061_;
  assign _0005_[14] = _0062_;
  assign _0005_[15] = _0063_;
  assign _0005_[16] = _0064_;
  assign _0005_[17] = _0065_;
  assign _0005_[18] = _0066_;
  assign _0005_[19] = _0067_;
  assign _0005_[20] = _0069_;
  assign _0005_[21] = _0070_;
  assign _0005_[22] = _0071_;
  assign _0005_[23] = _0072_;
  assign _0005_[24] = _0073_;
  assign _0005_[25] = _0074_;
  assign _0005_[26] = _0075_;
  assign _0005_[27] = _0076_;
  assign _0005_[28] = _0077_;
  assign _0005_[29] = _0078_;
  assign _0005_[30] = _0080_;
  assign _0005_[31] = _0081_;
  assign _0003_[0] = _0017_;
  assign _0003_[1] = _0018_;
  assign _0003_[2] = _0019_;
  assign _0003_[3] = _0020_;
  assign _0003_[4] = _0021_;
  assign _0003_[5] = _0022_;
  assign _0003_[6] = _0023_;
  assign _0003_[7] = _0024_;
  assign _0098_ = IDLin;
  assign _0002_[0] = _0009_;
  assign _0002_[1] = _0010_;
  assign _0002_[2] = _0011_;
  assign _0002_[3] = _0012_;
  assign _0002_[4] = _0013_;
  assign _0002_[5] = _0014_;
  assign _0002_[6] = _0015_;
  assign _0002_[7] = _0016_;
  assign _0097_ = IDLEOut_sintetizado;
  assign _0000_ = _0007_;
endmodule
