/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_paralelo.v:1" *)
module synth_paralelo(clk_4f, clk_32f, in_serial, valid_in, reset, out_serial_estructural);
  (* src = "synth_paralelo.v:11" *)
  wire _000_;
  (* src = "synth_paralelo.v:11" *)
  wire [2:0] _001_;
  (* src = "synth_paralelo.v:11" *)
  wire [2:0] _002_;
  (* src = "synth_paralelo.v:29" *)
  (* unused_bits = "3" *)
  wire [31:0] _003_;
  (* src = "synth_paralelo.v:46" *)
  (* unused_bits = "3" *)
  wire [31:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [1:0] _015_;
  wire _016_;
  wire [3:0] _017_;
  wire [1:0] _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [2:0] _024_;
  wire [2:0] _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:432" *)
  wire [7:0] _049_;
  (* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:428" *)
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire [2:0] _061_;
  wire [2:0] _062_;
  (* src = "synth_paralelo.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _063_;
  (* src = "synth_paralelo.v:46|paralelo_serial.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _064_;
  (* src = "synth_paralelo.v:41|paralelo_serial.v:33|<techmap.v>:445" *)
  wire _065_;
  (* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)
  wire _066_;
  (* src = "synth_paralelo.v:2" *)
  input clk_32f;
  (* src = "synth_paralelo.v:1" *)
  input clk_4f;
  (* src = "synth_paralelo.v:3" *)
  input [7:0] in_serial;
  (* src = "synth_paralelo.v:6" *)
  output out_serial_estructural;
  reg out_serial_estructural;
  (* src = "synth_paralelo.v:5" *)
  input reset;
  (* src = "synth_paralelo.v:8" *)
  reg [2:0] selector;
  (* src = "synth_paralelo.v:9" *)
  reg [2:0] selector_2;
  (* src = "synth_paralelo.v:4" *)
  input valid_in;
  assign _026_ = _007_ |(* src = "synth_paralelo.v:41|paralelo_serial.v:33" *)  _024_[2];
  assign _027_ = _008_ |(* src = "synth_paralelo.v:40|paralelo_serial.v:33" *)  _024_[2];
  assign _028_ = _009_ |(* src = "synth_paralelo.v:39|paralelo_serial.v:33" *)  _024_[2];
  assign _029_ = _010_ |(* src = "synth_paralelo.v:38|paralelo_serial.v:33" *)  _024_[2];
  assign _007_ = _004_[0] |(* src = "synth_paralelo.v:37|paralelo_serial.v:33" *)  _024_[1];
  assign _030_ = _007_ |(* src = "synth_paralelo.v:37|paralelo_serial.v:33" *)  selector[2];
  assign _008_ = selector[0] |(* src = "synth_paralelo.v:36|paralelo_serial.v:33" *)  _024_[1];
  assign _031_ = _008_ |(* src = "synth_paralelo.v:36|paralelo_serial.v:33" *)  selector[2];
  assign _009_ = _004_[0] |(* src = "synth_paralelo.v:35|paralelo_serial.v:33" *)  selector[1];
  assign _032_ = _009_ |(* src = "synth_paralelo.v:35|paralelo_serial.v:33" *)  selector[2];
  assign _033_ = _011_ |(* src = "synth_paralelo.v:24|paralelo_serial.v:16" *)  _025_[2];
  assign _012_ = selector_2[0] |(* src = "synth_paralelo.v:23|paralelo_serial.v:16" *)  _025_[1];
  assign _034_ = _012_ |(* src = "synth_paralelo.v:23|paralelo_serial.v:16" *)  _025_[2];
  assign _013_ = _003_[0] |(* src = "synth_paralelo.v:22|paralelo_serial.v:16" *)  selector_2[1];
  assign _035_ = _013_ |(* src = "synth_paralelo.v:22|paralelo_serial.v:16" *)  _025_[2];
  assign _036_ = _014_ |(* src = "synth_paralelo.v:21|paralelo_serial.v:16" *)  _025_[2];
  assign _011_ = _003_[0] |(* src = "synth_paralelo.v:20|paralelo_serial.v:16" *)  _025_[1];
  assign _037_ = _011_ |(* src = "synth_paralelo.v:20|paralelo_serial.v:16" *)  selector_2[2];
  assign _038_ = _012_ |(* src = "synth_paralelo.v:19|paralelo_serial.v:16" *)  selector_2[2];
  assign _039_ = _013_ |(* src = "synth_paralelo.v:18|paralelo_serial.v:16" *)  selector_2[2];
  assign _015_[0] = _048_ | _046_;
  assign _015_[1] = _045_ | _044_;
  assign _016_ = _015_[0] | _015_[1];
  assign _006_ = _016_ | _043_;
  assign _065_ = _005_ |(* src = "synth_paralelo.v:41|paralelo_serial.v:33|<techmap.v>:445" *)  _006_;
  assign _017_[0] = _049_[0] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _049_[1];
  assign _017_[1] = _049_[2] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _049_[3];
  assign _017_[2] = _049_[4] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _049_[5];
  assign _017_[3] = _049_[6] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _049_[7];
  assign _018_[0] = _017_[0] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _017_[1];
  assign _018_[1] = _017_[2] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _017_[3];
  assign _050_ = _018_[0] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:441" *)  _018_[1];
  assign _019_[0] = _052_ |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _053_;
  assign _019_[1] = _054_ |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _055_;
  assign _019_[2] = _056_ |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _057_;
  assign _019_[3] = _058_ |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _059_;
  assign _020_[0] = _019_[0] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _019_[3];
  assign _066_ = _020_[0] |(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *)  _020_[1];
  assign _021_ = _047_ | _042_;
  assign _005_ = _021_ | _041_;
  assign _010_ = selector[0] |(* src = "synth_paralelo.v:34|paralelo_serial.v:33" *)  selector[1];
  assign _022_ = _010_ |(* src = "synth_paralelo.v:34|paralelo_serial.v:33" *)  selector[2];
  assign _014_ = selector_2[0] |(* src = "synth_paralelo.v:17|paralelo_serial.v:16" *)  selector_2[1];
  assign _023_ = _014_ |(* src = "synth_paralelo.v:17|paralelo_serial.v:16" *)  selector_2[2];
  assign _041_ = ~(* src = "synth_paralelo.v:41|paralelo_serial.v:33" *) _026_;
  assign _042_ = ~(* src = "synth_paralelo.v:40|paralelo_serial.v:33" *) _027_;
  assign _043_ = ~(* src = "synth_paralelo.v:39|paralelo_serial.v:33" *) _028_;
  assign _044_ = ~(* src = "synth_paralelo.v:38|paralelo_serial.v:33" *) _029_;
  assign _045_ = ~(* src = "synth_paralelo.v:37|paralelo_serial.v:33" *) _030_;
  assign _046_ = ~(* src = "synth_paralelo.v:36|paralelo_serial.v:33" *) _031_;
  assign _047_ = ~(* src = "synth_paralelo.v:35|paralelo_serial.v:33" *) _032_;
  assign _048_ = ~(* src = "synth_paralelo.v:34|paralelo_serial.v:33" *) _022_;
  assign _052_ = ~(* src = "synth_paralelo.v:24|paralelo_serial.v:16" *) _033_;
  assign _053_ = ~(* src = "synth_paralelo.v:23|paralelo_serial.v:16" *) _034_;
  assign _054_ = ~(* src = "synth_paralelo.v:22|paralelo_serial.v:16" *) _035_;
  assign _055_ = ~(* src = "synth_paralelo.v:21|paralelo_serial.v:16" *) _036_;
  assign _056_ = ~(* src = "synth_paralelo.v:20|paralelo_serial.v:16" *) _037_;
  assign _057_ = ~(* src = "synth_paralelo.v:19|paralelo_serial.v:16" *) _038_;
  assign _058_ = ~(* src = "synth_paralelo.v:18|paralelo_serial.v:16" *) _039_;
  assign _059_ = ~(* src = "synth_paralelo.v:17|paralelo_serial.v:16" *) _023_;
  assign _001_[0] = reset ? (* src = "synth_paralelo.v:13" *) _062_[0] : 1'h0;
  assign _001_[1] = reset ? (* src = "synth_paralelo.v:13" *) _062_[1] : 1'h0;
  assign _001_[2] = reset ? (* src = "synth_paralelo.v:13" *) _062_[2] : 1'h0;
  assign _060_ = valid_in ? (* src = "synth_paralelo.v:14" *) _051_ : _040_;
  assign _000_ = reset ? (* src = "synth_paralelo.v:13" *) _060_ : 1'h0;
  assign _061_[0] = valid_in ? (* src = "synth_paralelo.v:14" *) _003_[0] : 1'h0;
  assign _061_[1] = valid_in ? (* src = "synth_paralelo.v:14" *) _003_[1] : 1'h0;
  assign _061_[2] = valid_in ? (* src = "synth_paralelo.v:14" *) _003_[2] : 1'h0;
  assign _002_[0] = reset ? (* src = "synth_paralelo.v:13" *) _061_[0] : 1'h0;
  assign _002_[1] = reset ? (* src = "synth_paralelo.v:13" *) _061_[1] : 1'h0;
  assign _002_[2] = reset ? (* src = "synth_paralelo.v:13" *) _061_[2] : 1'h0;
  assign _040_ = _065_ ? (* src = "synth_paralelo.v:41|paralelo_serial.v:33|<techmap.v>:445" *) _006_ : 1'hx;
  assign _051_ = _066_ ? (* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:445" *) _050_ : 1'hx;
  assign _062_[0] = valid_in ? (* src = "synth_paralelo.v:14" *) 1'h0 : _004_[0];
  assign _062_[1] = valid_in ? (* src = "synth_paralelo.v:14" *) 1'h0 : _004_[1];
  assign _062_[2] = valid_in ? (* src = "synth_paralelo.v:14" *) 1'h0 : _004_[2];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector[0] <= _001_[0];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector[1] <= _001_[1];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector[2] <= _001_[2];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector_2[0] <= _002_[0];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector_2[1] <= _002_[1];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      selector_2[2] <= _002_[2];
  (* src = "synth_paralelo.v:11" *)
  always @(posedge clk_32f)
      out_serial_estructural <= _000_;
  assign _064_[1] = selector[1] &(* src = "synth_paralelo.v:46|paralelo_serial.v:29|<techmap.v>:260|<techmap.v>:221" *)  selector[0];
  assign _024_[2] = selector[2] ^(* src = "synth_paralelo.v:38|paralelo_serial.v:33" *)  1'h1;
  assign _024_[1] = selector[1] ^(* src = "synth_paralelo.v:36|paralelo_serial.v:33" *)  1'h1;
  assign _004_[0] = selector[0] ^(* src = "synth_paralelo.v:35|paralelo_serial.v:33" *)  1'h1;
  assign _025_[2] = selector_2[2] ^(* src = "synth_paralelo.v:21|paralelo_serial.v:16" *)  1'h1;
  assign _025_[1] = selector_2[1] ^(* src = "synth_paralelo.v:19|paralelo_serial.v:16" *)  1'h1;
  assign _003_[0] = selector_2[0] ^(* src = "synth_paralelo.v:18|paralelo_serial.v:16" *)  1'h1;
  assign _049_[4] = in_serial[4] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _056_;
  assign _049_[7] = in_serial[7] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _059_;
  assign _049_[6] = in_serial[6] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _058_;
  assign _049_[5] = in_serial[5] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _057_;
  assign _049_[3] = in_serial[3] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _055_;
  assign _049_[2] = in_serial[2] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _054_;
  assign _049_[1] = in_serial[1] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _053_;
  assign _049_[0] = in_serial[0] &(* src = "synth_paralelo.v:24|paralelo_serial.v:16|<techmap.v>:434" *)  _052_;
  assign _003_[1] = selector_2[1] ^(* src = "synth_paralelo.v:29|<techmap.v>:263" *)  selector_2[0];
  assign _003_[2] = selector_2[2] ^(* src = "synth_paralelo.v:29|<techmap.v>:263" *)  _063_[1];
  assign _004_[1] = selector[1] ^(* src = "synth_paralelo.v:46|paralelo_serial.v:29|<techmap.v>:263" *)  selector[0];
  assign _004_[2] = selector[2] ^(* src = "synth_paralelo.v:46|paralelo_serial.v:29|<techmap.v>:263" *)  _064_[1];
  assign _063_[1] = selector_2[1] &(* src = "synth_paralelo.v:29|<techmap.v>:260|<techmap.v>:221" *)  selector_2[0];
  assign _003_[31:4] = 28'h0000000;
  assign _004_[31:4] = 28'h0000000;
  assign _024_[0] = _004_[0];
  assign _025_[0] = _003_[0];
  assign { _063_[31:2], _063_[0] } = { 29'h00000000, _003_[3], selector_2[0] };
  assign { _064_[31:2], _064_[0] } = { 29'h00000000, _004_[3], selector[0] };
endmodule
