/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* src = "sintetizado.v:3" *)
module sintetizado(data_in0, data_in1, data_in2, data_in3, valid0, valid1, valid2, valid3, clk, reset, active, valid_out_recirculador0, valid_out_recirculador1, valid_out_recirculador2, valid_out_recirculador3, recirculador_activo0, recirculador_activo1, recirculador_activo2, recirculador_activo3, recirculador_desactivado0, recirculador_desactivado1, recirculador_desactivado2, recirculador_desactivado3);
  (* src = "sintetizado.v:43" *)
  wire [7:0] _000_;
  (* src = "sintetizado.v:43" *)
  wire [7:0] _001_;
  (* src = "sintetizado.v:43" *)
  wire [7:0] _002_;
  (* src = "sintetizado.v:43" *)
  wire [7:0] _003_;
  (* src = "sintetizado.v:43" *)
  wire [7:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  (* src = "sintetizado.v:21" *)
  input active;
  (* src = "sintetizado.v:16" *)
  input clk;
  (* src = "sintetizado.v:6" *)
  input [7:0] data_in0;
  (* src = "sintetizado.v:7" *)
  input [7:0] data_in1;
  (* src = "sintetizado.v:8" *)
  input [7:0] data_in2;
  (* src = "sintetizado.v:9" *)
  input [7:0] data_in3;
  (* src = "sintetizado.v:30" *)
  output [7:0] sintetizado_activo0;
  (* src = "sintetizado.v:31" *)
  output [7:0] sintetizado_activo1;
  (* src = "sintetizado.v:32" *)
  output [7:0] sintetizado_activo2;
  (* src = "sintetizado.v:33" *)
  output [7:0] sintetizado_activo3;
  (* src = "sintetizado.v:36" *)
  output [7:0] sintetizado_desactivado0;
  (* src = "sintetizado.v:37" *)
  output [7:0] sintetizado_desactivado1;
  (* src = "sintetizado.v:38" *)
  output [7:0] sintetizado_desactivado2;
  (* src = "sintetizado.v:39" *)
  output [7:0] sintetizado_desactivado3;
  (* src = "sintetizado.v:18" *)
  input reset;
  (* src = "sintetizado.v:10" *)
  input valid0;
  (* src = "sintetizado.v:11" *)
  input valid1;
  (* src = "sintetizado.v:12" *)
  input valid2;
  (* src = "sintetizado.v:13" *)
  input valid3;
  (* src = "sintetizado.v:24" *)
  output valid_out_sintetizado0;
  (* src = "sintetizado.v:25" *)
  output valid_out_sintetizado1;
  (* src = "sintetizado.v:26" *)
  output valid_out_sintetizado2;
  (* src = "sintetizado.v:27" *)
  output valid_out_sintetizado3;
  NOT _151_ (
    .A(sintetizado_desactivado0[0]),
    .Y(_005_)
  );
  NAND _152_ (
    .A(reset),
    .B(active),
    .Y(_006_)
  );
  NOR _153_ (
    .A(_006_),
    .B(_005_),
    .Y(_004_[0])
  );
  NOT _154_ (
    .A(sintetizado_desactivado0[1]),
    .Y(_007_)
  );
  NOR _155_ (
    .A(_006_),
    .B(_007_),
    .Y(_004_[1])
  );
  NOT _156_ (
    .A(sintetizado_desactivado0[2]),
    .Y(_008_)
  );
  NOR _157_ (
    .A(_006_),
    .B(_008_),
    .Y(_004_[2])
  );
  NOT _158_ (
    .A(sintetizado_desactivado0[3]),
    .Y(_009_)
  );
  NOR _159_ (
    .A(_006_),
    .B(_009_),
    .Y(_004_[3])
  );
  NOT _160_ (
    .A(sintetizado_desactivado0[4]),
    .Y(_010_)
  );
  NOR _161_ (
    .A(_006_),
    .B(_010_),
    .Y(_004_[4])
  );
  NOT _162_ (
    .A(sintetizado_desactivado0[5]),
    .Y(_011_)
  );
  NOR _163_ (
    .A(_006_),
    .B(_011_),
    .Y(_004_[5])
  );
  NOT _164_ (
    .A(sintetizado_desactivado0[6]),
    .Y(_012_)
  );
  NOR _165_ (
    .A(_006_),
    .B(_012_),
    .Y(_004_[6])
  );
  NOT _166_ (
    .A(sintetizado_desactivado0[7]),
    .Y(_013_)
  );
  NOR _167_ (
    .A(_006_),
    .B(_013_),
    .Y(_004_[7])
  );
  NOT _168_ (
    .A(active),
    .Y(_014_)
  );
  NOT _169_ (
    .A(valid3),
    .Y(_015_)
  );
  NOR _170_ (
    .A(_015_),
    .B(_014_),
    .Y(_016_)
  );
  NOR _171_ (
    .A(_016_),
    .B(sintetizado_activo3[0]),
    .Y(_017_)
  );
  NOT _172_ (
    .A(data_in3[0]),
    .Y(_018_)
  );
  NAND _173_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _174_ (
    .A(_019_),
    .B(reset),
    .Y(_020_)
  );
  NOR _175_ (
    .A(_020_),
    .B(_017_),
    .Y(_003_[0])
  );
  NOR _176_ (
    .A(_016_),
    .B(sintetizado_activo3[1]),
    .Y(_021_)
  );
  NOT _177_ (
    .A(data_in3[1]),
    .Y(_022_)
  );
  NAND _178_ (
    .A(_016_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _179_ (
    .A(_023_),
    .B(reset),
    .Y(_024_)
  );
  NOR _180_ (
    .A(_024_),
    .B(_021_),
    .Y(_003_[1])
  );
  NOR _181_ (
    .A(_016_),
    .B(sintetizado_activo3[2]),
    .Y(_025_)
  );
  NOT _182_ (
    .A(data_in3[2]),
    .Y(_026_)
  );
  NAND _183_ (
    .A(_016_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _184_ (
    .A(_027_),
    .B(reset),
    .Y(_028_)
  );
  NOR _185_ (
    .A(_028_),
    .B(_025_),
    .Y(_003_[2])
  );
  NOR _186_ (
    .A(_016_),
    .B(sintetizado_activo3[3]),
    .Y(_029_)
  );
  NOT _187_ (
    .A(data_in3[3]),
    .Y(_030_)
  );
  NAND _188_ (
    .A(_016_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _189_ (
    .A(_031_),
    .B(reset),
    .Y(_032_)
  );
  NOR _190_ (
    .A(_032_),
    .B(_029_),
    .Y(_003_[3])
  );
  NOR _191_ (
    .A(_016_),
    .B(sintetizado_activo3[4]),
    .Y(_033_)
  );
  NOT _192_ (
    .A(data_in3[4]),
    .Y(_034_)
  );
  NAND _193_ (
    .A(_016_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _194_ (
    .A(_035_),
    .B(reset),
    .Y(_036_)
  );
  NOR _195_ (
    .A(_036_),
    .B(_033_),
    .Y(_003_[4])
  );
  NOR _196_ (
    .A(_016_),
    .B(sintetizado_activo3[5]),
    .Y(_037_)
  );
  NOT _197_ (
    .A(data_in3[5]),
    .Y(_038_)
  );
  NAND _198_ (
    .A(_016_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _199_ (
    .A(_039_),
    .B(reset),
    .Y(_040_)
  );
  NOR _200_ (
    .A(_040_),
    .B(_037_),
    .Y(_003_[5])
  );
  NOR _201_ (
    .A(_016_),
    .B(sintetizado_activo3[6]),
    .Y(_041_)
  );
  NOT _202_ (
    .A(data_in3[6]),
    .Y(_042_)
  );
  NAND _203_ (
    .A(_016_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _204_ (
    .A(_043_),
    .B(reset),
    .Y(_044_)
  );
  NOR _205_ (
    .A(_044_),
    .B(_041_),
    .Y(_003_[6])
  );
  NOR _206_ (
    .A(_016_),
    .B(sintetizado_activo3[7]),
    .Y(_045_)
  );
  NOT _207_ (
    .A(data_in3[7]),
    .Y(_046_)
  );
  NAND _208_ (
    .A(_016_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _209_ (
    .A(_047_),
    .B(reset),
    .Y(_048_)
  );
  NOR _210_ (
    .A(_048_),
    .B(_045_),
    .Y(_003_[7])
  );
  NOT _211_ (
    .A(valid2),
    .Y(_049_)
  );
  NOR _212_ (
    .A(_049_),
    .B(_014_),
    .Y(_050_)
  );
  NOR _213_ (
    .A(_050_),
    .B(sintetizado_activo2[0]),
    .Y(_051_)
  );
  NOT _214_ (
    .A(data_in2[0]),
    .Y(_052_)
  );
  NAND _215_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _216_ (
    .A(_053_),
    .B(reset),
    .Y(_054_)
  );
  NOR _217_ (
    .A(_054_),
    .B(_051_),
    .Y(_002_[0])
  );
  NOR _218_ (
    .A(_050_),
    .B(sintetizado_activo2[1]),
    .Y(_055_)
  );
  NOT _219_ (
    .A(data_in2[1]),
    .Y(_056_)
  );
  NAND _220_ (
    .A(_050_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _221_ (
    .A(_057_),
    .B(reset),
    .Y(_058_)
  );
  NOR _222_ (
    .A(_058_),
    .B(_055_),
    .Y(_002_[1])
  );
  NOR _223_ (
    .A(_050_),
    .B(sintetizado_activo2[2]),
    .Y(_059_)
  );
  NOT _224_ (
    .A(data_in2[2]),
    .Y(_060_)
  );
  NAND _225_ (
    .A(_050_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _226_ (
    .A(_061_),
    .B(reset),
    .Y(_062_)
  );
  NOR _227_ (
    .A(_062_),
    .B(_059_),
    .Y(_002_[2])
  );
  NOR _228_ (
    .A(_050_),
    .B(sintetizado_activo2[3]),
    .Y(_063_)
  );
  NOT _229_ (
    .A(data_in2[3]),
    .Y(_064_)
  );
  NAND _230_ (
    .A(_050_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _231_ (
    .A(_065_),
    .B(reset),
    .Y(_066_)
  );
  NOR _232_ (
    .A(_066_),
    .B(_063_),
    .Y(_002_[3])
  );
  NOR _233_ (
    .A(_050_),
    .B(sintetizado_activo2[4]),
    .Y(_067_)
  );
  NOT _234_ (
    .A(data_in2[4]),
    .Y(_068_)
  );
  NAND _235_ (
    .A(_050_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _236_ (
    .A(_069_),
    .B(reset),
    .Y(_070_)
  );
  NOR _237_ (
    .A(_070_),
    .B(_067_),
    .Y(_002_[4])
  );
  NOR _238_ (
    .A(_050_),
    .B(sintetizado_activo2[5]),
    .Y(_071_)
  );
  NOT _239_ (
    .A(data_in2[5]),
    .Y(_072_)
  );
  NAND _240_ (
    .A(_050_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _241_ (
    .A(_073_),
    .B(reset),
    .Y(_074_)
  );
  NOR _242_ (
    .A(_074_),
    .B(_071_),
    .Y(_002_[5])
  );
  NOR _243_ (
    .A(_050_),
    .B(sintetizado_activo2[6]),
    .Y(_075_)
  );
  NOT _244_ (
    .A(data_in2[6]),
    .Y(_076_)
  );
  NAND _245_ (
    .A(_050_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _246_ (
    .A(_077_),
    .B(reset),
    .Y(_078_)
  );
  NOR _247_ (
    .A(_078_),
    .B(_075_),
    .Y(_002_[6])
  );
  NOR _248_ (
    .A(_050_),
    .B(sintetizado_activo2[7]),
    .Y(_079_)
  );
  NOT _249_ (
    .A(data_in2[7]),
    .Y(_080_)
  );
  NAND _250_ (
    .A(_050_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _251_ (
    .A(_081_),
    .B(reset),
    .Y(_082_)
  );
  NOR _252_ (
    .A(_082_),
    .B(_079_),
    .Y(_002_[7])
  );
  NOT _253_ (
    .A(valid1),
    .Y(_083_)
  );
  NOR _254_ (
    .A(_014_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _255_ (
    .A(_084_),
    .B(sintetizado_activo1[0]),
    .Y(_085_)
  );
  NOT _256_ (
    .A(data_in1[0]),
    .Y(_086_)
  );
  NAND _257_ (
    .A(_084_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _258_ (
    .A(_087_),
    .B(reset),
    .Y(_088_)
  );
  NOR _259_ (
    .A(_088_),
    .B(_085_),
    .Y(_001_[0])
  );
  NOR _260_ (
    .A(_084_),
    .B(sintetizado_activo1[1]),
    .Y(_089_)
  );
  NOT _261_ (
    .A(data_in1[1]),
    .Y(_090_)
  );
  NAND _262_ (
    .A(_084_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _263_ (
    .A(_091_),
    .B(reset),
    .Y(_092_)
  );
  NOR _264_ (
    .A(_092_),
    .B(_089_),
    .Y(_001_[1])
  );
  NOR _265_ (
    .A(_084_),
    .B(sintetizado_activo1[2]),
    .Y(_093_)
  );
  NOT _266_ (
    .A(data_in1[2]),
    .Y(_094_)
  );
  NAND _267_ (
    .A(_084_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _268_ (
    .A(_095_),
    .B(reset),
    .Y(_096_)
  );
  NOR _269_ (
    .A(_096_),
    .B(_093_),
    .Y(_001_[2])
  );
  NOR _270_ (
    .A(_084_),
    .B(sintetizado_activo1[3]),
    .Y(_097_)
  );
  NOT _271_ (
    .A(data_in1[3]),
    .Y(_098_)
  );
  NAND _272_ (
    .A(_084_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _273_ (
    .A(_099_),
    .B(reset),
    .Y(_100_)
  );
  NOR _274_ (
    .A(_100_),
    .B(_097_),
    .Y(_001_[3])
  );
  NOR _275_ (
    .A(_084_),
    .B(sintetizado_activo1[4]),
    .Y(_101_)
  );
  NOT _276_ (
    .A(data_in1[4]),
    .Y(_102_)
  );
  NAND _277_ (
    .A(_084_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _278_ (
    .A(_103_),
    .B(reset),
    .Y(_104_)
  );
  NOR _279_ (
    .A(_104_),
    .B(_101_),
    .Y(_001_[4])
  );
  NOR _280_ (
    .A(_084_),
    .B(sintetizado_activo1[5]),
    .Y(_105_)
  );
  NOT _281_ (
    .A(data_in1[5]),
    .Y(_106_)
  );
  NAND _282_ (
    .A(_084_),
    .B(_106_),
    .Y(_107_)
  );
  NAND _283_ (
    .A(_107_),
    .B(reset),
    .Y(_108_)
  );
  NOR _284_ (
    .A(_108_),
    .B(_105_),
    .Y(_001_[5])
  );
  NOR _285_ (
    .A(_084_),
    .B(sintetizado_activo1[6]),
    .Y(_109_)
  );
  NOT _286_ (
    .A(data_in1[6]),
    .Y(_110_)
  );
  NAND _287_ (
    .A(_084_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _288_ (
    .A(_111_),
    .B(reset),
    .Y(_112_)
  );
  NOR _289_ (
    .A(_112_),
    .B(_109_),
    .Y(_001_[6])
  );
  NOR _290_ (
    .A(_084_),
    .B(sintetizado_activo1[7]),
    .Y(_113_)
  );
  NOT _291_ (
    .A(data_in1[7]),
    .Y(_114_)
  );
  NAND _292_ (
    .A(_084_),
    .B(_114_),
    .Y(_115_)
  );
  NAND _293_ (
    .A(_115_),
    .B(reset),
    .Y(_116_)
  );
  NOR _294_ (
    .A(_116_),
    .B(_113_),
    .Y(_001_[7])
  );
  NOT _295_ (
    .A(valid0),
    .Y(_117_)
  );
  NOR _296_ (
    .A(_117_),
    .B(_014_),
    .Y(_118_)
  );
  NOR _297_ (
    .A(_118_),
    .B(sintetizado_activo0[0]),
    .Y(_119_)
  );
  NOT _298_ (
    .A(data_in0[0]),
    .Y(_120_)
  );
  NAND _299_ (
    .A(_118_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _300_ (
    .A(_121_),
    .B(reset),
    .Y(_122_)
  );
  NOR _301_ (
    .A(_122_),
    .B(_119_),
    .Y(_000_[0])
  );
  NOR _302_ (
    .A(_118_),
    .B(sintetizado_activo0[1]),
    .Y(_123_)
  );
  NOT _303_ (
    .A(data_in0[1]),
    .Y(_124_)
  );
  NAND _304_ (
    .A(_118_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _305_ (
    .A(_125_),
    .B(reset),
    .Y(_126_)
  );
  NOR _306_ (
    .A(_126_),
    .B(_123_),
    .Y(_000_[1])
  );
  NOR _307_ (
    .A(_118_),
    .B(sintetizado_activo0[2]),
    .Y(_127_)
  );
  NOT _308_ (
    .A(data_in0[2]),
    .Y(_128_)
  );
  NAND _309_ (
    .A(_118_),
    .B(_128_),
    .Y(_129_)
  );
  NAND _310_ (
    .A(_129_),
    .B(reset),
    .Y(_130_)
  );
  NOR _311_ (
    .A(_130_),
    .B(_127_),
    .Y(_000_[2])
  );
  NOR _312_ (
    .A(_118_),
    .B(sintetizado_activo0[3]),
    .Y(_131_)
  );
  NOT _313_ (
    .A(data_in0[3]),
    .Y(_132_)
  );
  NAND _314_ (
    .A(_118_),
    .B(_132_),
    .Y(_133_)
  );
  NAND _315_ (
    .A(_133_),
    .B(reset),
    .Y(_134_)
  );
  NOR _316_ (
    .A(_134_),
    .B(_131_),
    .Y(_000_[3])
  );
  NOR _317_ (
    .A(_118_),
    .B(sintetizado_activo0[4]),
    .Y(_135_)
  );
  NOT _318_ (
    .A(data_in0[4]),
    .Y(_136_)
  );
  NAND _319_ (
    .A(_118_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _320_ (
    .A(_137_),
    .B(reset),
    .Y(_138_)
  );
  NOR _321_ (
    .A(_138_),
    .B(_135_),
    .Y(_000_[4])
  );
  NOR _322_ (
    .A(_118_),
    .B(sintetizado_activo0[5]),
    .Y(_139_)
  );
  NOT _323_ (
    .A(data_in0[5]),
    .Y(_140_)
  );
  NAND _324_ (
    .A(_118_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _325_ (
    .A(_141_),
    .B(reset),
    .Y(_142_)
  );
  NOR _326_ (
    .A(_142_),
    .B(_139_),
    .Y(_000_[5])
  );
  NOR _327_ (
    .A(_118_),
    .B(sintetizado_activo0[6]),
    .Y(_143_)
  );
  NOT _328_ (
    .A(data_in0[6]),
    .Y(_144_)
  );
  NAND _329_ (
    .A(_118_),
    .B(_144_),
    .Y(_145_)
  );
  NAND _330_ (
    .A(_145_),
    .B(reset),
    .Y(_146_)
  );
  NOR _331_ (
    .A(_146_),
    .B(_143_),
    .Y(_000_[6])
  );
  NOR _332_ (
    .A(_118_),
    .B(sintetizado_activo0[7]),
    .Y(_147_)
  );
  NOT _333_ (
    .A(data_in0[7]),
    .Y(_148_)
  );
  NAND _334_ (
    .A(_118_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _335_ (
    .A(_149_),
    .B(reset),
    .Y(_150_)
  );
  NOR _336_ (
    .A(_150_),
    .B(_147_),
    .Y(_000_[7])
  );
  DFF _337_ (
    .C(clk),
    .D(reset),
    .Q(valid_out_sintetizado1)
  );
  DFF _338_ (
    .C(clk),
    .D(_000_[0]),
    .Q(sintetizado_activo0[0])
  );
  DFF _339_ (
    .C(clk),
    .D(_000_[1]),
    .Q(sintetizado_activo0[1])
  );
  DFF _340_ (
    .C(clk),
    .D(_000_[2]),
    .Q(sintetizado_activo0[2])
  );
  DFF _341_ (
    .C(clk),
    .D(_000_[3]),
    .Q(sintetizado_activo0[3])
  );
  DFF _342_ (
    .C(clk),
    .D(_000_[4]),
    .Q(sintetizado_activo0[4])
  );
  DFF _343_ (
    .C(clk),
    .D(_000_[5]),
    .Q(sintetizado_activo0[5])
  );
  DFF _344_ (
    .C(clk),
    .D(_000_[6]),
    .Q(sintetizado_activo0[6])
  );
  DFF _345_ (
    .C(clk),
    .D(_000_[7]),
    .Q(sintetizado_activo0[7])
  );
  DFF _346_ (
    .C(clk),
    .D(_001_[0]),
    .Q(sintetizado_activo1[0])
  );
  DFF _347_ (
    .C(clk),
    .D(_001_[1]),
    .Q(sintetizado_activo1[1])
  );
  DFF _348_ (
    .C(clk),
    .D(_001_[2]),
    .Q(sintetizado_activo1[2])
  );
  DFF _349_ (
    .C(clk),
    .D(_001_[3]),
    .Q(sintetizado_activo1[3])
  );
  DFF _350_ (
    .C(clk),
    .D(_001_[4]),
    .Q(sintetizado_activo1[4])
  );
  DFF _351_ (
    .C(clk),
    .D(_001_[5]),
    .Q(sintetizado_activo1[5])
  );
  DFF _352_ (
    .C(clk),
    .D(_001_[6]),
    .Q(sintetizado_activo1[6])
  );
  DFF _353_ (
    .C(clk),
    .D(_001_[7]),
    .Q(sintetizado_activo1[7])
  );
  DFF _354_ (
    .C(clk),
    .D(_002_[0]),
    .Q(sintetizado_activo2[0])
  );
  DFF _355_ (
    .C(clk),
    .D(_002_[1]),
    .Q(sintetizado_activo2[1])
  );
  DFF _356_ (
    .C(clk),
    .D(_002_[2]),
    .Q(sintetizado_activo2[2])
  );
  DFF _357_ (
    .C(clk),
    .D(_002_[3]),
    .Q(sintetizado_activo2[3])
  );
  DFF _358_ (
    .C(clk),
    .D(_002_[4]),
    .Q(sintetizado_activo2[4])
  );
  DFF _359_ (
    .C(clk),
    .D(_002_[5]),
    .Q(sintetizado_activo2[5])
  );
  DFF _360_ (
    .C(clk),
    .D(_002_[6]),
    .Q(sintetizado_activo2[6])
  );
  DFF _361_ (
    .C(clk),
    .D(_002_[7]),
    .Q(sintetizado_activo2[7])
  );
  DFF _362_ (
    .C(clk),
    .D(_003_[0]),
    .Q(sintetizado_activo3[0])
  );
  DFF _363_ (
    .C(clk),
    .D(_003_[1]),
    .Q(sintetizado_activo3[1])
  );
  DFF _364_ (
    .C(clk),
    .D(_003_[2]),
    .Q(sintetizado_activo3[2])
  );
  DFF _365_ (
    .C(clk),
    .D(_003_[3]),
    .Q(sintetizado_activo3[3])
  );
  DFF _366_ (
    .C(clk),
    .D(_003_[4]),
    .Q(sintetizado_activo3[4])
  );
  DFF _367_ (
    .C(clk),
    .D(_003_[5]),
    .Q(sintetizado_activo3[5])
  );
  DFF _368_ (
    .C(clk),
    .D(_003_[6]),
    .Q(sintetizado_activo3[6])
  );
  DFF _369_ (
    .C(clk),
    .D(_003_[7]),
    .Q(sintetizado_activo3[7])
  );
  DFF _370_ (
    .C(clk),
    .D(_004_[0]),
    .Q(sintetizado_desactivado0[0])
  );
  DFF _371_ (
    .C(clk),
    .D(_004_[1]),
    .Q(sintetizado_desactivado0[1])
  );
  DFF _372_ (
    .C(clk),
    .D(_004_[2]),
    .Q(sintetizado_desactivado0[2])
  );
  DFF _373_ (
    .C(clk),
    .D(_004_[3]),
    .Q(sintetizado_desactivado0[3])
  );
  DFF _374_ (
    .C(clk),
    .D(_004_[4]),
    .Q(sintetizado_desactivado0[4])
  );
  DFF _375_ (
    .C(clk),
    .D(_004_[5]),
    .Q(sintetizado_desactivado0[5])
  );
  DFF _376_ (
    .C(clk),
    .D(_004_[6]),
    .Q(sintetizado_desactivado0[6])
  );
  DFF _377_ (
    .C(clk),
    .D(_004_[7]),
    .Q(sintetizado_desactivado0[7])
  );
  assign sintetizado_desactivado1 = 8'b00000000;
  assign sintetizado_desactivado2 = 8'b00000000;
  assign sintetizado_desactivado3 = 8'b00000000;
  assign valid_out_sintetizado0 = valid_out_recirculador1;
  assign valid_out_sintetizado2 = valid_out_recirculador1;
  assign valid_out_sintetizado3 = 1'b0;
endmodule
